### ISSUE TITLE
App Configuration on iPad only visible when "Allow Multiple Apps" is set

### ISSUE THREAD

**Issue by gerard33** [home-assistant/iOS#1049]
Model Name: iPad
Software Version: iOS 14.0
App version: 2020.6.1 (2)

**Home Assistant Core Version**
0.115.1

**Describe the bug**
The App Configuration in the sidebar is only shown when you enable "Allow Multiple Apps" in the iOS settings.
This setting can be found here: `Settings > Home Screen & Dock > Multitasking > Allow Multiple Apps`

**To Reproduce**
See above.

**Expected behavior**
If that setting is off then you want know why the App Configuration is not shown. Maybe a warning can be added so the user knows that the setting has to be changed?

As discussed with @TomBrien on Discord.

**Comment by zacwest** [comment]
This appears to be an Apple bug (filed as FB8720708) where it says the system supports multiple scenes (windows, effectively) but it actually does not. I can probably work around it.

**Comment by mountainsandcode** [comment]
As an alternative, is it possible to retain the iPhone way of handling the app configuration with an overlay pop up rather than a separate window just on iPad and keep the multi-window option on Mac?

I personally find that the separate window on iPad just for configuration adds limited value. Also, the only way to close that window is to go to the app switcher and kill it (I guess it’s not strictly required to close it but feels like the standard workflow somehow)

**Comment by zacwest** [comment]
My plan is to go back to how it opened settings before on iPad, as a modal and not a separate window.
