### ISSUE TITLE
App seem to fail with iOS 14

### ISSUE THREAD

**Issue by m4k5ym** [home-assistant/iOS#1067]
**iOS device model, version and app version**

Model Name: iPhone 11 Pro Max
Software Version: 14
App version: latest (2020 09 21st)

**Home Assistant Core Version**

0.114.4
**Describe the bug**
After App has been started page stays blank like in the given screenshot.
**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/38684218/93805777-75a7d680-fc48-11ea-98b1-39021e462d7d.jpeg)
**Additional context**

**Comment by mshli** [comment]
I have the same problem. In my case, i can say it is a DNS problem. 

I have defined an URL for my homeassistant, which will be resolved from my internal DNS server with the private address if i‘m in my local Wifi. And if i‘m outside of my Wifi, my public DNS server resolves the URL with my public IP address. 

![1EAEC457-2767-44EA-8B96-28CDE0FBFC53](https://user-images.githubusercontent.com/6434389/93945941-4375a200-fd38-11ea-9ee1-c9b174e5482d.jpeg)


This setup worked for me until i updated to IOS14. Since then, my Iphones always uses an external DNS server to resolve my URL.

**Comment by m4k5ym** [comment]
Somehow the issue resolved after app has been reinstalled and reconfigured however the configuration was not removed with deletion. iOS 14 seem to be fun as every major iOS release...

**Comment by m4k5ym** [comment]
Problem seems to resolved it self since it seemed to be an iOS related problem.
