### ISSUE TITLE
Extra Large Complication not all working correct

### ISSUE THREAD

**Issue by skycryer** [home-assistant/iOS#1165]
**iOS device model, version and app version**
Model Name: Apple Watch Series 6
Software Version: Apple Watch OS 7.0.1
App version: 2020.6.2 (1)

Model Name: iPhone 11 pro
Software Version: iOS 14.1
App version: 2020.6.2 (1)

**Home Assistant Core Version**
0.115.6

**Describe the bug**
Complications on Extra Large not working correct.
- Ring image not showing ring or icon
- Ring text not showing ring
- Simple image not showing icon
- Stack image not showing icon

**To Reproduce**
Add complications from top to X-Large Watchface.

**Expected behavior**
Show missing ring and icon data

**Comment by mountainsandcode** [comment]
May be related to #1127

**Comment by TomBrien** [comment]
Due to the throttling of complication updates, these can take quite a while to start working. I wouldn't expect them to work straight away (clearly this needs improving). Can you try leaving the face with a complication selected active (screen can turn off just don't change face) for a few hours and see what happens then. You c an also try [these steps](https://companion.home-assistant.io/docs/apple-watch/apple-watch#manual-sync-procedure)

**Comment by skycryer** [comment]
@TomBrien the text on Ring text for example shows after manual sync direct, only the ring is missing
