### ISSUE TITLE
watchOS: error when running shortcut with a "perform action" provided by Home Assistant

### ISSUE THREAD

**Issue by gitmirko** [home-assistant/iOS#1195]
**iOS device model, version and app version**
Model Name: Apple Watch Series 3 (A1859)
Software Version: watchOS 7.0
App version: 2020.6.2 (1)

**Home Assistant Core Version**
0.116.2

**Describe the bug**
When I try to use a shortcut on the watch that contains a "perform action" provided by Home Assistant, I will get a "Remote user isn't registered" error message. The same shortcut works without problems on my iPhone (iPhone 8; iOS 14.0).

**To Reproduce**
Create shortcut with a "perform action" provided by Home Assistant and run it on the watch.

**Expected behavior**
I would expect the shortcut running without errors on the watch as well.

**Comment by zacwest** [comment]
I do not believe this error is coming from the app but is instead coming from the Watch. Do you have any other Shortcuts that you could test that aren't Home Assistant ones?

**Comment by gitmirko** [comment]
I have other Shortcuts and they work fine. I thought it has to be related to Home Assistant.

**Comment by gitmirko** [comment]
I've just upgraded to iOS 14.0.1 and watchOS 7.0.2 and the error is gone. Sorry for the inconvenience.

**Comment by gitmirko** [comment]
Unfortunatley it stopped working short after my last comment. It started working again for a couple of times after upgrading to iOS 14.1 and watchOS 7.0.3. Is there a way to debug this issue further? Could someone else replicate this issue?

**Comment by bloodrave** [comment]
Having the same issue since I updated watchOS to 7.3.2, iOS to 14.4.1 and HA app 2021.77. Works fine with the BETA app 2021.76 (Idk why the version is lower)

**Comment by bloodrave** [comment]
Just left the BETA and the issue is no longer reproducing

**Comment by zacwest** [comment]
The only difference between the latest beta release is localized string changes, and that is only because I forgot to push the newer one to beta too.

I believe this issue is iOS or the Watch having connectivity issues. However, the forthcoming 2021.4 update does fix a crasher in Shortcuts handling which may or may not be a factor.

**Comment by bloodrave** [comment]
The shortcuts were working fine on the phone, the watch seemed to run them from the phone as the error stated, I tried to make some other shortcuts but they all seem to run on the watch or give an error they are not supported on it. Seemed to have been caused by the app update, but might be something on the OS part. I think offloading and reinstalling the app might fix this. Or going beta and out of beta as I did.

**Comment by gitmirko** [comment]
I've tried every combination listed on this thread but no luck at all. Same error as reported last October.

**Comment by Danielson89** [comment]
I had a shortcut that opened a chrome browser which failed and gave me that unregistered thing but when I create the shortcut URL to open in Safari it works,  I noticed that chrome isn't installed on my apple watch so maybe if the app isn't available on the apple watch it won't work??

**Comment by gitmirko** [comment]
> I had a shortcut that opened a chrome browser which failed and gave me that unregistered thing but when I create the shortcut URL to open in Safari it works, I noticed that chrome isn't installed on my apple watch so maybe if the app isn't available on the apple watch it won't work??

The app is the home assistant app itself which is installed on the watch and works just fine.

**Comment by bgoncal** [comment]
Is this still an issue in 2024? Let me know and I will reopen it
