### ISSUE TITLE
Add sensor for macOS to show which display is primary

### ISSUE THREAD

**Issue by JonLaliberte** [home-assistant/iOS#1247]
**Describe the solution you'd like**
A new sensor for the current primary display ID.

I switch which display is primary based on how/where I'm working (on the same machine). This would enable me to set an automation up to change lighting/other devices in my offices based on it.

**Additional context**
Right now I use [cscreen](https://www.pyehouse.com/cscreen/) in Keyboard Maestro to get this info. The output is something like this:
    DisplayID  Index     Depth     Width     Height  Refresh
      ca0001       1        32      2560       1440    60
     42be4a0       2        32      2560       1440     0

The display with index 1 is the primary display. 
This same utility allows changing of the primary display like so: cscreen -i 42be4a0 -p

**Comment by efficiencynerd** [comment]
+1, I'd like this as well. I only have my external monitor plugged in at my work desk, so it would be nice to trigger my office lights to come on when this monitor is plugged in.

**Comment by zacwest** [comment]
`NSScreen.screens` seems like a good analog for what we need:

**A unique identifier**
- Created via `CGDisplayCreateUUIDFromDisplayID(screen.deviceDescription["NSScreenNumber"])`
- Unclear if this UUID is truly guaranteed to be unique, but it e.g. returns nil when the screen number is invalid, so presumably it is looking it up somewhere.

**A localized name**
`localizedName` returns e.g. `"Built-in Retina Display"`

**Whether it has the menu bar**
The first screen in `NSScreen.screens` is documented as having the menu bar.

-----

Theres a few things worth considering on how to make useful sensors out of this:
- We don't know any persisted information about past-connected displays, so creating e.g. `sensor.[device]_[display_id]` with an on/off would likely get wrong very quickly.
- We can't store array values in the sensor value, so something like `sensor.[device]_displays` with multiple display IDs or names as the value wouldn't work.

This may be another case of needing to abuse attributes to get more info, since we need to handle a variety of states. We could do something like:

- `sensor.[device]_displays` with a value of the number of sensors, with attributes like `Display Names` and `Display IDs`
- `sensor.[device]_primary` with a value of the name of the has-menu-bar display, with attributes like `Display ID`

I feel like this balances well the "I want to just know I'm docked" (more than 1 display) and "I want to know _where_ I'm docked" (which display name) for most external display uses.
