### ISSUE TITLE
auto refresh notification push-id upon re-install

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/iOS#1580]
**Is your feature request related to a problem? Please describe.**

Whenever the App gets re-installed (on many devices its gets archived automatically when not used over a period of time)
the following message is displayed in the HA logs:
```
 [homeassistant.components.mobile_app.notify] Requested entity was not found. This message is generated externally to Home Assistant.
```

in our household, this pertains to devices not in the home, but of outbound family members... Who I have to ask time and time again, to manually refresh the notification push id

**Describe the solution you'd like**

Would be very nice if the above process could be handled automatically, making it a way less intrusive device-tracker...
Especially since these family members don't have a clue why this is, or what they are doing. The simply want to use the App, and, tbh, they shouldn't have to handle these technical things.

**Additional context**

**Comment by zacwest** [comment]
Unless the app gets launched after it is uninstalled and reinstalled, it has no mechanism to trigger this push update. Launching the app will do this - has that not been your experience? The next time it occurs, retrieving debug logs would be helpful.

**Comment by Mariusthvdb** [comment]
> has that not been your experience
tbh, I am not really sure. I see the messages roll in but even after I did a push refresh. There's only 1 other device that could be needing the refresh, but it is not targeted at all for a notification....

would I need to set the debug on `homeassistant.components.mobile_app` ? or on `homeassistant.components.mobile_app.notify`

**Comment by Mariusthvdb** [comment]
It is happening when the push rate is displayed:
```
2021-04-13 11:49:56 INFO (MainThread) [homeassistant.components.mobile_app.notify] mobile_app push notification rate limits for iPad Red: 7 sent, 500 allowed, 0 errors, resets in 14:10:03
2021-04-13 11:49:56 INFO (MainThread) [homeassistant.components.mobile_app.notify] mobile_app push notification rate limits for iPad van Me: 7 sent, 500 allowed, 0 errors, resets in 14:10:03
2021-04-13 11:49:57 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Requested entity was not found. This message is generated externally to Home Assistant.
2021-04-13 11:49:57 INFO (MainThread) [homeassistant.components.mobile_app.notify] mobile_app push notification rate limits for Mijn mobiel: 7 sent, 500 allowed, 0 errors, resets in 14:10:02
2021-04-13 11:49:57 INFO (MainThread) [homeassistant.components.mobile_app.notify] mobile_app push notification rate limits for Telefoon: 7 sent, 500 allowed, 0 errors, resets in 14:10:02
2021-04-13 11:49:58 INFO (MainThread) [homeassistant.components.mobile_app.notify] mobile_app push notification rate limits for MacBook Pro: 7 sent, 500 allowed, 0 errors, resets in 14:10:01
2021-04-13 11:49:59 INFO (MainThread) [homeassistant.components.mobile_app.notify] mobile_app push notification rate limits for Ipad Pro: 7 sent, 500 allowed, 0 errors, resets in 14:10:00
2021-04-13 11:49:59 INFO (MainThread) [homeassistant.components.mobile_app.notify] mobile_app push notification rate limits for CallTheBoss: 9 sent, 500 allowed, 0 errors, resets in 14:10:00
2021-04-13 11:49:59 INFO (MainThread) [homeassistant.components.mobile_app.notify] mobile_app push notification rate limits for CIA: 7 sent, 500 allowed, 0 errors, resets in 14:10:00
```

which als positively identifies the missing App bearer. That is to me, not in the log obviously.

**Comment by zacwest** [comment]
Which device isn't in the list there? That will be the one which errorred - the rest look successful.

We need to first identify that so we can figure out why its push id has gone invalid. If it is because the app was uninstalled, nothing we can do remotely will make it re-register.

If the app is still installed and launching, it should be keeping its push id up-to-date whenever it starts up.

This will not caused failed logins. Those should include the User-Agent which I have only seen be the frontend in bug reports.

**Comment by Mariusthvdb** [comment]
not sure if it called uninstalled exactly in Apple terms, but upon longer time of not using, Apple seems to 'archive' an app so ti doesn't take space. 
When they (my kids) the open the app once more, it gets re-instated, and the push_id needs to be  cleared/refreshed. 
Hope my explanation its clear enough to understand for you, sorry for the layman wording.

So no, its not mine, but I can see it again (my daughter made it to the app-settings and refreshed ;-) Dont have any debug logs I am afraid. They are not available in the integrations logs on my HA instance?

About the failed logins: thats just the thing, whenever that happens it says to check the logs, but there's nothing at all in the logs. Could you advize me which components to set debug on for any failed login to appear in the log?

**Comment by zacwest** [comment]
> not sure if it is called 'uninstalled' exactly in Apple terminology, but upon longer time of not using, Apple seems to 'archive' an app so it doesn't take space.
> 
> When they (my kids) the open the app once more, it gets re-instated, and the push_id needs to be cleared/refreshed. In the listing above, I can of course positively identify the device, because I know which one I am not seeing ;-)

When the app is launched, it updates the server with the latest push id, and as of a few releases of HA ago, this causes the notify service to be reloaded. What this means is that what you're asking for already should be happening.

If this is _not_ the case, there's 2 pieces of information we can combine:

1. What is the push id of the device?
2. What is the push id the server thinks the device should have?

If these two differ, any attempt to push will result in an error, so it's useful to know what the state of the client is because that should inform which error case we're in.

I'm unsure if the offloaded apps you're referring to continue to support push notifications. Presumably that's not a feature Apple would turn off when unloaded, which means whatever you're experiencing is different than normal.

So for _that_ reason, and the push id reason, it would be useful to have logs from the client as well. Just the latest run will do. In the App Configuration, you can export the logs as a .zip file, and you can [drop them here](https://www.dropbox.com/request/CtVWqILBXZ41tmFSGK2y) to add them to my Dropbox. I'll delete them after reviewing, and nobody else will see. It will contain information like GPS locations -- you may want to redact it.

> About the failed logins: thats just the thing, whenever that happens it says to check the logs, but there's nothing at all in the logs.

Failed login logs will include the User-Agent, so you can see what is causing them. If it includes the "like Safari" string, that's the frontend causing it.

> Lastly, when does this listingnin the logs occur? Is it a timed happening, or does it happen based on an action in the HA instance, trying to notify the clients? In which case I wouldn't understand that, because I dont try to notify them at all. Or, is this happening upon a refresh of the devices states in the HA integration maybe.

Only when you send a notification to the `notify.mobile_app_xyz`. This includes the `notify.notify` service as well.

**Comment by Mariusthvdb** [comment]
wow, thanks for you answer, much appreciated!

> If this is not the case,

I guess not.. 
Will have to take some time to be able to supply you with all the logs you need, so please be patient ;-) But this specific device has been reset now, so I guess I have to wait until the next time this happens?

> Failed login logs will include the User-Agent, so you can see what is causing them. If it includes the "like Safari" string, that's the frontend causing it.

with regular log level: error, I don't see anything in the logs, only the persistent notification... I just received another invalid login and an Ip ban was issued because of that. Nothing in the logs however....

> Only when you send a notification to the notify.mobile_app_xyz. This includes the notify.notify service as well.

Since I don't send any notification over mobile_app to all registered devices, I take it this must be a notify.notify notification?
Will have to scrutinize those, because I cant think of an hourly message right now..

Anyways, Ive got work to do, thanks!
