### ISSUE TITLE
Error with Eureka when Interoperating with Objective-C

### ISSUE THREAD

**Issue by NoahNetex** [home-assistant/iOS#1802]
I am currently working on a fork of HomeAssistant trying to integrate Objective C code into my application. Part of this process involves calling Swift code from an Objective C class. To do this, I have to import the generated Objective-C header file that Xcode makes for the Swift code, "HomeAssistant-Swift.h". This produces an error to the affect of the following, "Cannot find interface declaration for 'EurekaFormViewController', superclass of 'HAFormViewController'". How can I either tell Xcode to ignore the Eureka pod's swift interface or fix the error that it is causing?

**To Reproduce**
Create an Objective-C '.m' file. Add this line to the file to import the generated Objective-C header file:
```objective-c
#import "HomeAssistant-Swift.h"
```
Now run the project and the error should pop up.

**Comment by zacwest** [comment]
I'm guessing it's because the project is set up to not create the appropriate headers for Objective-C bridging:

https://github.com/home-assistant/iOS/blob/dcc15a19c4ffe7a088194a907a687f61448d5be5/Configuration/HomeAssistant.xcconfig#L16

You'll need to turn this on, and figure out what kind of issues it might cause (especially for Catalyst), to write Objective-C code in the application. Another option is to create a `.framework` module with the Objective-C code which can be imported as a module in the Swift code.
