### ISSUE TITLE
iOS App runs in timeout during app setup; AlamoFire

### ISSUE THREAD

**Issue by Mitch66745** [home-assistant/iOS#1918]
First setup of a fresh installed App version. 

When selecting the server entry from auto-discovery I am asked for credentials. Which are accepted. The connection then runs into a timeout - error code: alamofire.AFError 13

When I do the same but enter the server address manually it works like a charm. Only reproducible with the server entry from auto-discovery.

Versions:
** core-2021.11.3
** supervisor-2021.10.8
** Home Assistant OS 6.6 on RPI
iPad mini 6 with OS version 15.1

**Comment by zacwest** [comment]
Does the IP address shown in the discovery list match the one you are entering manually?

**Comment by Mitch66745** [comment]
Yes, that is the strange part. It discovers the correct IP:port.

**Comment by mralexhenry** [comment]
Same problem here. tried a lot of things to no avail, and noticed that an unofficial iOS app works fine (though this alternative app sucks), so I think this may be a bug in the current iOS

**Comment by zacwest** [comment]
Please share the exact error message you are receiving.

**Comment by Cr1515b** [comment]
having the same issue. I am getting the following error when trying to connect.
`Failed to connect
URLSessionTask failed with error: The request timed out.

Error code:
Alamofire.AFError 13`

**Comment by Breakingx** [comment]
Same Problem. 15.0.2 IOS Version.
With an android phone everything works fine.

**Comment by intra-au** [comment]
Same issue on iOS 15.1.1, Discovers docker container on Synology, click on discovered server, shows login and password prompts, enter credentials and hit "Login". Login window disappears and sits with spinning thing for a minute or more, then message URLSessionTask failed with error: The request timed out. Error Code: Alamofire.AFError 13
Server is accessible via browser just fine and works as expected.

**Comment by JelleMarc** [comment]
Anyone got this fixed? Running into the same issue. Up to date iOS iPhone 13 Pro

**Comment by LordNex** [comment]
Question. I just did a rebuild of my network with new WAPs, Switch's, and a Firewalla Gold firewall. I have my network segmented into 4 VLANs; LAN, Main, IoT, and Guest.

My server is a Dell PowerEdge R620 with 4 Intel NICs teamed together running VMWare ESXi 7.0.3. 

The only way I could figure out how to get Home Assistant to see the other VLANs was to add additional port groups on the virtual switch in VMWare with each of the VLANs represented. I then went into the VMWare VMs settings for HA and added 4 total NICs. Each one specifying a different VLAN. Each connection has its own IP address associated with that VLAN. So I have a total of 4 ip addresses listed under HostName and zip AddressesI'm also trying to setup DuckDNS with LetsEncrypt and AdGuard as a local DNS server to do local DNS Rewrites. 

I can logon to HA by specific IP addresses but not via domain name. Also, anytime I try and use the IOS companion app it doesn't see the server automatically, and if I specify the address, I get the cannot connection error 500 message. 

Anyone have any idea what's going on here or does anyone have a good way of setting home Assistant up with a segmented VLAN network so that it can gather data from all VLANs?

**Comment by figentropy** [comment]
Has anyone solved this issue?  Works great on my Android phone.  I even had it working on my iphone.  But after deleting the app and reinstalling it, I'm no longer able to connect the iphone app.  I'm getting the following error:  URLSessionTask failed with error: A server with the specified hostname could not be found.  Error Code: Alamofire.AFError 13

**Comment by GoblinRules** [comment]
> 

I was able to solve the error by first connecting internally via the IP (without https) and then in the APP setting → Server → External URL I removed the check mark for Home Assistant Cloud.

Even after a reinstallation, the check mark seemed to be still set

As mentioned [here ](https://community.home-assistant.io/t/home-assistant-companion-ios-alamofire-aferror-13/430169/8?u=goblinrules)
