### ISSUE TITLE
Basic auth in addition to native auth?

### ISSUE THREAD

**Issue by jschlyter** [home-assistant/iOS#193]
I'm trying to get HTTP Basic Auth working for my HASS (iOS app v1.5.0 (34) beta from Testflight and HASS v0.84.6). When validating the connection, the webview asks for the basic auth username/password and then continues to the normal hass login.

Questions:
- Is the Basic Auth setting the iOS app used _in addition_ to the native HASS auth (as en extra layer of security), or is the Basic Auth meant to replace the native auth?
- How can I help debugging this further?

**Comment by robbiet480** [comment]
Hi @jschlyter,

After auditing the HTTP basic auth code (I didn't write it) I've found a few holes that i've patched. However, I have been unable to properly test HTTP Basic I believe due to random 401's on the API. Can you share your setup details, including configuration, so I can get a working test environment going?

For reference, here's my relevant NGINX config:

```nginx
server {
  listen 8124;

  proxy_buffering off;

  auth_basic "Home Assistant Basic Auth";
  auth_basic_user_file /usr/local/etc/nginx/htpasswd;

  location / {
    proxy_set_header Authorization "Bearer TOKEN";
    proxy_pass http://localhost:8123;
    proxy_set_header Host $host;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
  }

  location /api/websocket {
    proxy_set_header Authorization "Bearer TOKEN";
    proxy_pass http://localhost:8123/api/websocket;
    proxy_set_header Host $host;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
```

Also, just to be perfectly honest here, I am strongly considering HTTP Basic Authentication from the app since it was implemented just before the new authentication system thus it is no longer required as much. But, if I can get a test setup going, I guess i'm okay with leaving it in the app with the understanding that it is not recommended and could break randomly.

**Comment by robbiet480** [comment]
Also, to directly answer at least Q1, yes, you should be able to use basic auth in concert with native auth

**Comment by jschlyter** [comment]
I'm using https://caddyserver.com/ with the following `Caddyfile`:

     hass.example.com {
       tls user@example.com
       basicauth / username password
       proxy / localhost:8123 {
         transparent
         websocket
       }
     }

For the moment, I'm using the above without the "basicauth" part and it 
works just fine (although exposing HASS a bit too much to the 
Intertubes).

**Comment by rcarz** [comment]
@robbiet480 It would be disappointing if basic authentication was removed. I'd like to use it for device-level authentication in place of client certs on iOS. As I mentioned in #16, the `Authorization` header isn't being sent so the server responds with `401 Authorization Required` as expected. 

I've tried with both the legacy API password and the token authentication scheme to no avail. Unfortunately I'm not set up to do iOS development but I'm happy to help you test builds. The nginx configuration you're using above should work fine.

@jschlyter You're using the basic auth fields in the iOS app configuration screen? Basic auth works fine for me in the webview but the app doesn't appear to send the `Authorization` header. I don't understand how this is working for you.

**Comment by robbiet480** [comment]
@jschlyter @rcarz Thanks to both of you for your feedback.

@jschlyter I tried your Caddyfile, it works just like nginx does. I get an initial HTTP Basic auth request, complete it, login to HA, then once i'm on the dashboard I get a bunch more authentication requests, I assume from the ServiceWorker driving all the HA API interaction on the frontend. Is this what you see as well?

**Comment by jschlyter** [comment]
@robbiet480 Indeed, but that seems to be the case for normal webtraffic to the frontend as well. The "normal" requests work as expected, but all background API calls fails. I wonder if Basic Auth is doomed due to this.

@rcarz To clarify, it does not work with basic auth at the moment - neither with the iOS app nor with a webbrowser.

**Comment by robbiet480** [comment]
Following up on this, I'm again leaning towards removing basic auth as of 2.0 as it will feature amazing support for `mobile_app` which enables the app to send _all_ requests via a single URL that has been hardened for security. Even better, if you subscribe to Nabu Casa it will become a "cloudhook" automatically, so you will never need to have a open port in your router again! 

My recommendation for those using basic auth is to either stop entirely in favor of closing the port in their router and using a Cloudhook or to carve out a basic auth exception for the webhook routes that `mobile_app` will use.

How does this sound to y'all?

**Comment by benleb** [comment]
The problem with this is, afaik it is basically a piece of untested code (in comparison to nginx which serves billions of request probably every hour or day)  which has the responsibility to keep people away from your very personal data, power plugs, maybe cameras...
And nabu casa... I never saw any numbers but as far as i know just very few people used it or even still use it. So please, keep the Basic Auth. robbie 👍

Off-topic... any release date estimates for the 2.0? ;)

**Comment by rcarz** [comment]
@robbiet480 I prefer to open a port than rely on a third party system so the cloud hook option has no appeal to me. Is there a technical reason you prefer to remove basic auth? I'm sure the hardened URLs are a great feature, but I trust nginx far more than a relatively immature codebase with full access to my home's lighting and other systems. Ideally I would like to use client certs, but the WebKit bug is preventing that on iOS. I think the next best option is basic auth.

**Comment by nferch** [comment]
I'm unable to get HTTP Basic Auth + Native auth working in 1.5.1 from the app store. I'm using a very simple nginx config similar to what @robbiet480 included above. It works fine from a desktop web browser but when I try and "Validate and Save Connection Settings" in the app I get prompted several times for credentials and eventually it fails.

Count me in as one who would prefer basic auth as a perimeter security control.

**Comment by jschlyter** [comment]
Let me just emphasize the importance of the extra layer of security that HTTP Basic Auth would provide. I urge @robbiet480 to make the necessary adjustments to support this before the next release - it would help people exposing their instances on the public Internet significantly.

**Comment by benleb** [comment]
Pushing people to trust a single authority was always something HA was fighting against, but Basic Auth has to die for Nabu Casa?  🤷‍♀️ 😢

**Comment by stianeikeland** [comment]
Home-assistant is a fast paced code base, and while it 99% likely is perfectly safe, we never know what might show up down the road. A tiny mistake or wrong assumption might (worst case) turn into a worm-able vulnerability. Many people don't upgrade home-assistant regularly either.

Security is built in layers. Adding a layer of basic auth makes so much sense here. What's the chance that there's an exploitable vulnerability in BOTH nginx and home-assistant? :)

We ought to be able to change the lock to our house.. Or use two locks if we feel paranoid.

**Comment by baurmatt** [comment]
I absolutely agree. Putting an additional layer of security in front of home assistant should be a requirement for security minded people if you think about what they might control with it (door lock, webcam, ...).

**Comment by FireFrei** [comment]
I would agree that basic auth is necessary for a secure self-hosted environment.
Let me explain why from my point of view:
During the last years I have invested much time to build up a secure home network environment for automation and IoT devices, using separate VLANs, firewall rules and so on. It does not feel right to open "uncontrolled" access from the internet to a device or a service within "the heart of my home zone": Home Assistant.
Home Assistant has done a lot right in its design to make it a secure service while still offering a lot of features to its users. I think the service by Nabu Casa is the right way - for people who "just want to do home automation", but do not care about the rest. It's easy and has a well designed integration.
But for all other people who are love home assistant by its privacy and all-local/cloud-less design, it should still be possible to host and/or secure everything them self.

Let's compare it with a company: From my experience in a security concept you would never offer a public service by opening and forwarding a port directly to an internal server. Not even when filtering and whitelisting only a single url. Because, if you are in, you are in. They would firewall the service and put it in a DMZ, then forward authorized requests from the DMZ to the internal network.

As its not really possible to apply the DMZ architecture here, you could provide an extra layer of security with basic auth:
User <-> Webserver Apache/Nginx or HAProxy w. BasicAuth <->  HA instance
or:
Attacker <-> Webserver (<-> HA instance).

Finally, I would really love to have the possibility to add a second layer of security - so that I can sleep better ;-) The easiest here wold be BasicAuth I guess, as TLS Client Certs don't work on iOS..., VPN has to be established each time, ... 

Last but not least, thanks to all home assistant developers for your great work!

**Comment by doridave** [comment]
Hi, 

New user of Home Assistant, longtime user of OpenHab, and HA is a breath of fresh air. Really digging it and migrating everything over.

Today I configured my external access and Nginx rev proxy worked great until I tried basic auth over the top which of course led me here!

Is this a thing, 6 months on? I strongly agree with the sentiment in this thread. 

Niether the web app in Chrome on my mobile, nor the Android v 1.9.0-167 were happy with my meddling when basic auth was on. 

Manged to get the Android App to work just once with basic auth, by using the https://proxuser:pass@hassdomain.here inthe app config home assistant URL field.   
After that one time, it refused after restarting the app and will spam requests for the basic auth credentials, but not actually work when entered, it will spam with 'unable to connect to home assistant' as you enter creds. 

The prox logs indicate user"-" being passed back by the Android App so it 401's..

Firefox, will accept a request with the above fulls creds in the URL method too and log in, this is so far what I'm using but hoping to get the app working for push notifications.

Im fairly certain all the config is what it'd need to be, there are a number of services exposed behind the rev proxy and Hass does work once I remove the basic auth. 

Anyone know the formula to get the Android App to work with basic auth? 

Running HassOS 4.9 and 0.110.5 core and as mentioned Android v 1.9.0-167

Thanks dev's this is an excellent app, loving the availability of tools for when I stuff up it tells me why and how! How many wasted hours on other platforms where debug tools barely exist.

**Comment by robbiet480** [comment]
The latest I have to say on this: Still not opposed to adding but same issues remain. WebSockets don't support basic auth on iOS. I am happy to accept a PR to add basic auth, but as its something I personally don't use, I have no interest in adding it myself.

**Comment by derekatkins** [comment]
Could we use client certs instead of Basic Auth?

**Comment by zacwest** [comment]
Logistically speaking I do not believe this is _possible_ to implement basic auth in the app in a way that isn't either difficult to understand or significantly less secure.

The HTTP protocol uses the [`Authorization` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization) for both basic (value like `Basic <base64>`) and token (value like `Bearer <token>`) authentication, which means we would be unable to simultaneously send a 'basic auth' value and an API token to API requests, which must work to use the app.

Practically speaking this means you would need to either (1) disable authentication on your Home Assistant instance for the API, or (2) encode your authorization token in your reverse proxy.

**Comment by benleb** [comment]
any news here? :>

**Comment by matteofranceschini** [comment]
AFAIK, only a parallel discussion with a workaround solution for android: https://github.com/home-assistant/android/issues/526

**Comment by nferch** [comment]
Agreed on the point regarding the `Authorization` header.

Assuming solutions like client TLS certificates (PKI too complicated to set up and manage), or other hacks such as putting a secret in a custom HTTP header, perhaps a slightly better solution would be to encode a secret token in the URI for the API endpoint? This value could be checked on the HomeAssistant HTTP server or checked and rewritten on the reverse proxy.

This isn't a great solution as it would be security by obscurity and a bit hacky, but I'm not too keen to expose something as powerful as HomeAssistant or something that presents the opportunity to laterally traverse into my home network without some additional protection, especially something that could be programmatically discovered as noted above.

**Comment by mietzen** [comment]
> (2) encode your authorization token in your reverse proxy.

Sorry for digging this out. You mean the API Token, right?
What would be the downside of this?

**Comment by leonklingele** [comment]
Can this please be reopened? Basic Auth + native login-based auth still doesn't work together, even not with the aforementioned nginx hack.

**Comment by marc4s** [comment]
Absoultly. it should be repoened and in a first step it should be possible to setup the "Home Assistant URL" in a standard format which excepts

http://username:password@server.domain/path

**Comment by theotherp** [comment]
I didn't solve the basic auth problem but went a different way: I allow to authenticate using a certificate which is safer anyway. Part of my nginx config:

```
auth_basic_user_file /etc/nginx/.htpasswd;
ssl_client_certificate ca.crt;
ssl_verify_client optional;
if ($ssl_client_verify = SUCCESS) {
	set $auth_basic off;
}
if ($ssl_client_verify != SUCCESS) {
	set $auth_basic Restricted;
}
auth_basic $auth_basic;
```

If authentication is done via cert then basic auth is skipped. You need to import the user certificate for the server certificate on your phone. This also works on Android. You can test it in your browser before you enter it in the companion app.

See https://www.ssltrust.com.au/help/setup-guides/client-certificate-authentication for more information on how to create the certificate.

**Comment by marc4s** [comment]
sounds great. can you give some more details how you created the certs? I used this:
https://gist.github.com/alexishida/607cca2e51ec356b1fe1909047ec70fd

but I had no success using the ca.crt in nginx and client in browser. i did the other way around. client.crt in nginx and ca.crt in browser which worked. but this is not correct i think and not secure maybe.

and i have issues importing the ca.crt and the client.p12 in android. it is not accepted. if i create it without a passphrase android is asking for and is not accepting an empty password. then i created with an 8character password and still not accepted. then with 12characters and still not accepted

**Comment by marc4s** [comment]
ok. solution for android is conerting the p12 in a compatible format:

https://stackoverflow.com/questions/71872900/installing-pcks12-certificate-in-android-wrong-password-bug

**Comment by lnxbil** [comment]
> This also works on Android.

Unfortunately, it does not work in iOS due to the hardened security. Each App needs to provide its own keystore for certificates and no 3rd party app has access to the default phone keystore. It'll work with Safari and that is what I use for the better part of this year. Unfortunately, the companion app is still not able to embedd the certificate itself. Basic Auth is also still not working, however you will not get an error anymore if you provide the correct password in the url scheme, but a faulty webpage with only HA logo and no login mask. I suppose this is the problem others mentioned due to the different authentication schemes used.

**Comment by DaAwesomeP** [comment]
Another version of @theotherp's [solution](https://github.com/home-assistant/iOS/issues/193#issuecomment-1636783285) but using Nginx's `map` instead of `if` (possibly more performant, avoids if--see ["If is Evil"](https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/)):

In the `server` section or if using the Nginx addon in a file that matches `nginx_proxy_default*.conf`:
```conf
ssl_client_certificate /ssl/ca.crt;
ssl_verify_client optional;

auth_basic $hass_auth_basic;
auth_basic_user_file /share/.htpasswd; 
```

Outside of the `server` section or in a file in `nginx_proxy/ if using the Nginx addon:
```conf
map $ssl_client_verify $hass_auth_basic {
  "SUCCESS"  "off";
  default    "closed site";
}
```

And be sure to generate your `.htpasswd` using bcrypt passwords instead of MD5 (the default!):
```bash
htpasswd -B /share/.htpassword some_user_device_name
```

I give each device either a client certificate (`prime256v1`) or a unique basic auth user/password with a long password (48 characters or so). I do it by device (not user) so that I can revoke one easily.

This solution has the same behavior as [the previous one above](https://github.com/home-assistant/iOS/issues/193#issuecomment-1636783285) where devices are first prompted for a certificate (if they support it) and only if certificate auth fails/skips they are prompted for user/password. This works well for the Android app (which supports client certificates but not basic auth) and the iOS app (which supports basic auth but not client certificates). Desktop web browsers and OSes tend to support certificates easily, but this solution lets you choose either!

Note that your server's mains certificates do not need to be signed by the CA specified in `ssl_client_certificate` (you can use letsencrypt or similar), so you won't see any warnings or need to make exclusions on the clients.

**Comment by daverof** [comment]
> and the iOS app (which supports basic auth but not client certificates).

This is huge news - how did you get basic auth working on the iOS app? Using your config I'm still getting the message:

`Failed to Connect - HTTP Basic Authentication is unsupported` which is how it's always been.

**Comment by joeydh** [comment]
Same here, I don't get why they dont just allow basic auth to the URL it's so weird to block that. Can't they just parse the URL normally and it should work

**Comment by DaAwesomeP** [comment]
> This is huge news - how did you get basic auth working on the iOS app?

Very very sorry, not trying to spread wrong information. I had not tried it in iOS yet and I misinterpreted the various previous threads. I now understand that it worked at one point but now does not.

I'm going to work on a solution that excludes basic auth/client cert checking on the specific endpoints that don't support it on iOS. I think I will also try aliasing Home Assistant to a unique subdirectory for each iOS client like `myhome.example.com/AABBCCDD..123456.../`. Since it is all over HTTPS I think this is similar security to basic auth except that the passwords will be stored in plaintext (not a bcrypt hash) on the Nginx side and the password will be clearly shown in the external URL in the app.

So to summarize what I am going to try next:

- Move password to subdirectory alias
- In this subdirectory do not require basic auth/cert auth for specific iOS endpoints if the user agent matches iOS

The iOS device I am trying to get to work belongs to someone else in my household, and I can't really touch it until I have it all working, so I need to see if I can virtualize it somehow. I'll post my next attempt so others can try as well.

For someone with an iOS device--does the app prompt at all for basic auth credentials but then fails to work with the WebSocket parts (the Android app does this), or does it not prompt for basic auth at all?

**Comment by DaAwesomeP** [comment]
@joeydh my understanding now from above is that the APIs use token based/bearer authentication which makes use of the same HTTP header as basic auth. Client certificates would be the best solution, but unlike on Android this seems to be more difficult on iOS (apps cannot use the system certificate store it seems). I'm now trying to figure out alternate ways to pass a password or token to Nginx.

**Comment by DaAwesomeP** [comment]
OK, a day of attempts and I _nearly_ got it but alas could not.

My attempt:

1. iOS user visits `https://my-home.example.com/secret_unique_long_random_string_for_user` by entering it into the connection URL box
2. Nginx sets a device-specific cookie that lasts a very long time if the device is a Home Assistant app (identified by the secret path and user agent)
3. User is redirected to `https://my-home.example.com/` and is allowed to view without client certificate or basic auth because of the cookie

This works wonderfully in any desktop browser, but the iOS app has a few issues:

- Seems to be an iOS issue in general--it does not like `ssl_client_verify optional;` option in Nginx and treats it as if the client certificate is required. This means I would need two subdomains or two ports to make this work (one for iOS w/o certs and one for Android w/ certs). Nginx does not allow variables or location blocks for the `ssl_client_verify` option, so I can't just use another `map` by user agent.
 - iOS webview does not always pass the cookies when dynamically loading assets. For this reason I had to always allow access to `/static/` and `/frontend_latest` if the user agent matched iOS (side note: I think it also doesn't pass basic auth credentials, as I also saw only a logo when I discovered this).
  - I could not get the initial login webview to put Home Assistant in the User Agent, so I had to match all Mac/iPhone devices (see #2512).
  - I am successfully able to login and the initial webview closes, but Alamofire does not like seeing a redirect (either `302` or `303`) when it tries to connect again after successful authentication.
  - If I initially connect with the internal URL and then switch in preferences to only using the cookie-protected one as external, then everything except WebSockets seems to work--it for some reason removes the first `/` and tries to open `https://my-home.example.comapi/webhook/...`. This is probably related to the path in the connection URL or the redirect and is probably fixable in the iOS app.

So where does that leave us?

- **Client certificates would be the best solution but are tricky to implement on iOS (hopefully one day it can work!)**
- We cannot use HTTP basic auth because that header is already in use by Home Assistant with bearer auth for some URLs.
- Setting a cookie did not seem to work (this could potentially be fixed but it would be a band-aid for an already ugly hack).
 - A possible solution would be to add support for setting HTTP proxies and the `Proxy-Authenticate` header (which would not interfere with the existing bearer auth), but this is almost certainly more complicated.
- **I think the simplest, most feasible solution would be at to add a custom header field.** This header would be sent whenever the beginning of the URL fully matches either the internal or external Home Assistant URLs (don't want to send it to other URLs that could be embedded in Lovelace).

I think for now I will figure out setting up Tailscale. This is a bit unfortunate since the setup for each iOS device will not be plug-and-play.

<details>
<summary>Details of my attempt in a spoiler because it is very long and didn't work (click here to expand):</summary>

In the `server` section or if using the Nginx addon in a file that matches `nginx_proxy_default*.conf`:
```nginx
ssl_client_certificate /ssl/ca.crt;

# iOS unfortunately doesn't like even optional cert prompting
# This would require two server blocks or two ports to listen on to support both certs and cookies
ssl_verify_client off;
# ssl_verify_client optional;

auth_basic_user_file /share/.htpasswd; 

auth_basic $hass_request_uri_ios_companion_auth_basic;  # See comment for this mapped variable
#auth_basic $hass_auth_useragent_auth_cookie_auth_cert_auth_basic;

location /another_secret_string_112233/ {
  auth_basic $hass_auth_useragent_auth_cert_auth_basic;
  try_files DUMMY_DOES_NOT_EXIST @valid_user_01;  # Can't use return here or it overrides auth_basic
}

location @valid_user_01 {
  add_header Set-Cookie "__Host-hass_custom_auth_cookie=another_secret_string_445566; Secure; HttpOnly; SameSite=Strict; Path=/; Max-Age=315600000";
  return 302 $scheme://$http_host$request_uri_without_top_dir; # Can't use rewrite or won't set cookie/send headers
}
```

Outside of the `server` section or in a file in `nginx_proxy/` if using the Nginx addon:
```nginx
variables_hash_bucket_size 128;

# Check for cert, otherwise basic auth
map $ssl_client_verify $hass_auth_cert_auth_basic {
  "SUCCESS"  "off";
  default    "closed site";
}

# Check for cookie, otherwise cert/basic auth
map $http_cookie $hass_auth_cookie_auth_cert_auth_basic {
  "~(?:^|; )__Host-hass_custom_auth_cookie=another_secret_string_445566(?:$|; )" "off";
  default $hass_auth_cert_auth_basic;
}

# Check for user agent then cookie, otherwise cert/basic auth
map $http_user_agent $hass_auth_useragent_auth_cookie_auth_cert_auth_basic {
  "~^Home(?:%20| )Assistant/" $hass_auth_cookie_auth_cert_auth_basic;
  "~ \(Macintosh; " $hass_auth_cookie_auth_cert_auth_basic;  # see home-assistant/#2512
  "~ \(iPhone; " $hass_auth_cookie_auth_cert_auth_basic;  # see home-assistant/#2512
  default                     $hass_auth_cert_auth_basic;
}

# Check for user agent, otherwise cert/basic auth
map $http_user_agent $hass_auth_useragent_auth_cert_auth_basic {
  "~^Home(?:%20| )Assistant/" "off";
  "~ \(Macintosh; " "off";  # see home-assistant/#2512
  "~ \(iPhone; " "off";  # see home-assistant/#2512
  default                     $hass_auth_cert_auth_basic;
}

# For redirecting after successfully setting a cookie
map $request_uri $request_uri_without_top_dir {
    "~^/(?:[^/\n]+)/(.*)$"  $1;
    default $request_uri;
}

# iOS webview does not send cookies to dynamically loaded assets
# This is in a map instead of location blocks to avoid redefining all of the proxy pass options
map $request_uri $hass_request_uri_ios_companion_auth_basic {
  "~^/frontend_latest/(.*)$" $hass_auth_useragent_auth_cert_auth_basic;
  "~^/static/(.*)$" $hass_auth_useragent_auth_cert_auth_basic;
  default $hass_auth_useragent_auth_cookie_auth_cert_auth_basic;
}
```

</details>

**Comment by msx80** [comment]
> Absoultly. it should be repoened and in a first step it should be possible to setup the "Home Assistant URL" in a standard format which excepts
> 
> http://username:password@server.domain/path

yeah why is this not allowed? It would solve basic auth and let the app work the native login just like it does today.

I'm trying to configure basic+native but the android app breaks, it says it's unable to connect.

I want to have basic auth for added security, expecially to hide the fact that there's a home assistant instance running behind the url.
