### ISSUE TITLE
When removing a server from the companion app, the app gets really slow and eventually crashes.

### ISSUE THREAD

**Issue by Calimerorulez** [home-assistant/iOS#2169]
Running HAOS 2022.8.1, supervisor 2022.07.0, iOS companion app beta 2022.6 (2022.375), on an iPhone 11, iOs 15.6.

When I remove a server from the app, the app gets very slow, freezes and then eventually crashes. The server isn't removed from the app.

On older iOS versions, the behaviour is the same, it crashes too, also with a SIG_CRASH.

**Comment by bemble** [comment]
Latest official versions, no more crash for me neither app getting slow. But I cannot remove a server, it brings back few minutes after, even if the server is down (I setup a dev server to fix front issues on mobile, so I had to add the dev server in my app).
It's an issue to me because I created an Siri shortcut to open my garage door and now it always ask me on which server to apply the actions:

https://user-images.githubusercontent.com/397503/195280923-d2899e8a-3663-4bef-bcbf-dec269912e56.MP4

**Comment by zacwest** [comment]
This is fixed by #2190
