### ISSUE TITLE
After upgrading to iOS 16 .0 my notification mobile name changed

### ISSUE THREAD

**Issue by jmwhite5** [home-assistant/iOS#2202]
My iPhone device name is "JM's iPhone" (as shown in General ➔ About ➔ Name)

My mobile notification service name used to be: "notify.mobile_app_jms_iphone".

But now, after get iOS update, the name has changed to mobile_app_iphone.  (the "jms_" part is gone).

I haven't changed anything else, and now my automations are failing.   I'm running the latest everything else:
Home Assistant 2022.9.2
Supervisor 2022.08.6
Operating System 8.5
Frontend 20220907.0 - latest

**Comment by bluestreak101** [comment]
I have the same issue. Two phones, mine and my wife's. Both of which were updated to iOS16 and since broke the notification settings as the notification device changes names.

I have managed to get one of them working again but only after the iOS app prompted me to enter a new name on my iPhone when re-connecting the app to the server as there was already a device named iPhone connected.

I now have Bills iPhone and iPhone as two entries in the Mobile App integration. However I would like to be able to use the device name as entered in the iPhones name field. This is what appears to be broken. The Mobile App is not pulling the name from the iPhone settings, its instead defaulting to iPhone.

If we cannot get the app to automatically pull from this field how do we prompt to enter a device name when connecting?

**Comment by jsiemek** [comment]
Zack wrote quite some time ago:

iOS 16 introduces a new privacy feature which disallows the app from knowing your device name. This means your notify target for all devices on iOS 16 is renamed to either notify.mobile_app_iphone or notify.mobile_app_ipad.

Workaround: Rename your device in the app's Settings > [Server] > Device Name.

**Comment by TomBrien** [comment]
This is a known issue. Please see #2148 or the instruction [here](https://companion.home-assistant.io/docs/troubleshooting/faqs/#ios-16-device-name-missing-from-notify-service-andor-entities)

**Comment by jmwhite5** [comment]
Thank you all!  All working fine for me.
