### ISSUE TITLE
Third-party authentication fails due to invalid User-Agent in HA iOS app

### ISSUE THREAD

**Issue by djonk** [home-assistant/iOS#2244]
**Context**
I've a Home Assistant installation that is secured behind [Cloudflare's Zero Trust](https://dash.teams.cloudflare.com/) platform and uses a Cloudflare Tunnel to be exposed to the outside world. It is setup so that Zero Trust Application policies require Authentication through an Authentication provider like Okta, Google, Azure AD, etc. 

**Problem**
The setup works just fine with the iOS app if you use simple authentication (e.g., Code through Email). Third-part authentication providers, like Google, check the User-Agent of the browser which is non-standard, thus denying the request. 

<img width="380" alt="image" src="https://user-images.githubusercontent.com/2938616/198435226-1b221c43-db4d-4e68-a75a-a4cc519117e9.png">

**Solution**
Use a standard User Agent that is widely accepted and not seen as a security risk by third-party authentication providers. 

**Version**
Home Assistant for iOS v. 2022.10

**Comment by zacwest** [comment]
The app does not support these authentication methods for more reasons than just the User-Agent (which will not be changed for this; authentication itself would need to be rewritten to provide credentials and avoid loading e.g. Google into the WebView - that's the core of the issue here). See https://github.com/home-assistant/iOS/discussions/1719
