### ISSUE TITLE
MacOS app is a terrible resource hog with memory leaks

### ISSUE THREAD

**Issue by spitfire** [home-assistant/iOS#2359]
Model Name: MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
macOS Version: 13.3.1 (a) (22E772610a)
App Version: 2023.4
Safari Version: 16.4 (18615.1.26.110.1)

**Home Assistant Core Version**
2023.5.2

**Describe the bug**
MacOS app is a terrible resource hog with memory leaks. 

**To Reproduce**
Let it run for a while and look at the Activity monitor

**Expected behavior**
It should not use over 50% of a CPU core constantly, nor should it eat multiple gigabytes of RAM.

**Screenshots**
<img width="736" alt="Zrzut ekranu 2023-05-10 o 20 58 13" src="https://github.com/home-assistant/iOS/assets/42872/95018d94-e5f6-48af-8d7e-d20b283ad803">
<img width="982" alt="Zrzut ekranu 2023-05-10 o 21 05 51" src="https://github.com/home-assistant/iOS/assets/42872/76698be4-c451-40af-b3e8-f4b84d69ca15">

**Additional context**
None.

**Comment by Nicomagno** [comment]
I have the same problem. Mainly Memory usage, so much that ssd fills with swap memory.


Model Name: MacBook Pro (16-inch, 2021 )
macOS Version: 13.4
App Version: 2023.460 (had this same problem since 2021 since I have an Apple silicon Mac, but checked It happens in intel Macs too)
Safari Version: 16.5 (18615.2.9.11.4)

Home Assistant Core Version
2023.5.4 (but I had the same problem since 2021)
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 

interface Add ons used:
[auto-entities](https://github.com/hacs/repository/167744584)
[Secondaryinfo Entity Row](https://github.com/hacs/repository/159711605)
[fold-entity-row](https://github.com/hacs/repository/150781994)
[mini climate card](https://github.com/hacs/repository/268163975)

Statistic graph
Gauges
surveillance camera footage

Initially I thought it was Apex-Charts visualization add on,
then I thought it was Graphana windows mixed in the UI,
Now I only use Statistics graph. but the problem persists.

Describe the bug
MacOS app is a terrible resource hog with memory leaks.

To Reproduce
Let it run for a while and look at the Activity monitor

Expected behavior
It should not eat multiple gigabytes of RAM (when opening app ~1.5gb that's a lot but ok, but randomly increases up to 100gb using ssd swap) .

**Comment by spitfire** [comment]
this is also true on an M1 MacBook Air. What are you doing Home Assistant app? You're taking most CPU time for any app, more than WindowServer (window/desktop management/display server and most system services combined):
<img width="458" alt="Zrzut ekranu 2023-10-14 o 21 54 07" src="https://github.com/home-assistant/iOS/assets/42872/d66079c8-b4ec-4047-b13b-78a910127993">

**Comment by pszypowicz** [comment]
Macbook Pro M1 Pro: 39GB Ram Usage.

![image](https://github.com/home-assistant/iOS/assets/2733699/3e9a6dbd-237f-492c-b142-2c253655e99e)

**Comment by MacDada** [comment]
* MacBook Pro M1 Pro, 14" 2021
* MacOS Sonoma 14.3.1 (23D60)
* Home Assistant Companion App 2024.2 (2024.561)
* HA Core 2024.2.5, Supervisor 2024.03.1, Operating System 12.1, Frontend 20240207.1

I've just woke up my macbook from sleep and noticed it is not responsive at all. After a few "frozen" minutes, the window appeared:
![Screenshot 2024-04-01 at 18 46 39](https://github.com/home-assistant/iOS/assets/136261/38617675-3e11-4010-a02d-23fe97fdaad1)

Notice, HA Companion App for Mac taking 45 GB of RAM.

![Screenshot 2024-04-01 at 18 47 34](https://github.com/home-assistant/iOS/assets/136261/1aa0ad58-531f-4455-9bab-3251453056ea)
![Screenshot 2024-04-01 at 18 48 01](https://github.com/home-assistant/iOS/assets/136261/e5c60bfb-3a76-4296-9ec8-683069ee1292)

Also notice: `WindowServer` taking 31.5 GB -> after I killed HA Companion App, it is now showing "only" 1.25 GB.

![Screenshot 2024-04-01 at 18 48 48](https://github.com/home-assistant/iOS/assets/136261/6e514f77-8b9a-48b3-bde3-3d201b5038bd)

 https://community.home-assistant.io/t/substantial-memory-leak-in-the-ha-app/605207

**Comment by andersonvom** [comment]
Same issue here. The companion app starts consuming ~60MB of RAM and
slowly keeps on consuming more memory, even without any interaction (just
idling in the background).

**MacBook Pro:** Apple M3 Max, 16-inch, Nov 2023
**MacOS:** Sonoma 14.2.1 (23C71)
**HA Companion App:** 2024.3 (2024.608)
**HA Core:** 2024.3.0
**HA Frontend:** 20240306.0

Here's the log of memory snapshots over time I'm seeing on my machine: [memory-usage.csv](https://github.com/home-assistant/iOS/files/14938081/memory-usage.csv). I don't know this show any causal relationship, but I plotted the memory usage vs time between measurements (in intervals of 5min) over the course of a week, and indicated how long it took between measurements to highlight times where the computer went to sleep. One possible correlation is that, when the computer slept for many hours, there was a huge spike in memory consumption. See the graph below:

![memory-vs-date](https://github.com/home-assistant/iOS/assets/69922/5ae436f2-5bab-4467-a26c-317c42f36f85)

**Comment by bgoncal** [comment]
Let's keep the discussion flowing in this duplicate issue: https://github.com/home-assistant/iOS/issues/2101
Thank you all for providing data
