### ISSUE TITLE
Hide "Send Location" shortcut ?

### ISSUE THREAD

**Issue by frenchzed** [home-assistant/iOS#2664]
**iOS device model, version and app version**
Model Name: iPhone 15 Pro
Software Version: iOS 17.4
App version: 2024.2

**Home Assistant Core Version**
2024.561

**Describe the bug**
I disable everything location related that I could in the App and in Home Assistant zone, and I still see the "Send Location" shortcut. Is there any way to get rid of it ?

![image](https://github.com/home-assistant/iOS/assets/4069230/aed64bd7-b53b-43bb-a63f-ada7ef2a080d)

**To Reproduce**

* Disabled everything in the Location settings (see screenshot)
* Disabled Home zone tracking with `track_ios: false`

![image](https://github.com/home-assistant/iOS/assets/4069230/3aaef4ea-a84b-4945-b3db-eefcc953c939)

**Expected behavior**

I was expecting to see the "Send Location" shortcut gone, as it should be basically useless as soon as the Location Permission is disabled (I don't think disabling anything else really matters).

**Comment by bgoncal** [comment]
Thanks for the feedback, this is expected and it was implemented to be a fixed app icon action, but I have noted your feedback and if implemented I'll make sure to add in the release notes.

I'll close this issue because we dont track feature requests in GitHub (even though this is small), use Home Assistant Community page to request new features.
