### ISSUE TITLE
Disconnected: Did not receive auth message within 10 seconds - Since the latest iOS app update

### ISSUE THREAD

**Issue by alexsaas** [home-assistant/iOS#2675]
When I get home and open the app, it can't connect to Home Assistant. And screen displays the following message: Unable to connect to Home Assistant.

![image](https://github.com/home-assistant/iOS/assets/153439645/72e9e87d-a83d-4528-918a-71810d012209)

When I close it completely and restart, it works again and the logs show the following error:

````

Logger: homeassistant.components.websocket_api.http.connection
Quelle: components/websocket_api/http.py:461
Integration: Home Assistant WebSocket API (Dokumentation, Probleme)
Erstmals aufgetreten: 18:30:40 (1 Vorkommnisse)
Zuletzt protokolliert: 18:30:40

[140141174576832] from IPADRESS (Mozilla/5.0 (iPhone; CPU iPhone OS 17_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2024.3 (io.robbie.HomeAssistant; build:2024.608; iOS 17.3.1) Mobile/HomeAssistant, like Safari): Disconnected: Did not receive auth message within 10 seconds

````
iOS device model: iPhone 11 Pro
iOS Version: 17.3.1
App version: 2024.3 build 608

Home Assistant Core Version: 2024.3.1

**Comment by alexsaas** [comment]
Addendum: I don't use remote access.

**Comment by mbo18** [comment]
Same here since last update, multiple time per day:

```
Logger: homeassistant.components.http.ban
Source: components/http/ban.py:128
integration: HTTP (documentation, issues)
First occurred: 16:29:02 (1 occurrences)
Last logged: 16:29:02

Login attempt or request with invalid authentication from md-1.home (10.2.10.30). Requested URL: '/api/websocket'. (Mozilla/5.0 (iPhone; CPU iPhone OS 17_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2024.3 (io.robbie.HomeAssistant; build:2024.608; iOS 17.4.1) Mobile/HomeAssistant, like Safari)
```

**Comment by ShadowRep** [comment]
Same here.

Most of the time I have to force close the app and start it fresh.
Sometimes even multiple times.

**Comment by alams154** [comment]
I am also seeing this issue on the latest update on an iPhone 13 Pro Max

**Comment by bgoncal** [comment]
Can you test 2024.3 build 612?

**Comment by alexsaas** [comment]
@bgoncal The earliest I could do that is in 8-9 hours when I get back home. However, I don't see a new version in the German App Store yet?

**Comment by bgoncal** [comment]
Ok sorry I thought you were testing the beta already, so you are experiencing that with latest App Store version? If you wish to try the beta: https://testflight.apple.com/join/1AlPbnLZ

**Comment by alexsaas** [comment]
Yes, with the latest current App Store version from last week. I have still tested beta versions on iOS. I'll have to take a look at it first. How it goes.

**Comment by mbo18** [comment]
> Ok sorry I thought you were testing the beta already, so you are experiencing that with latest App Store version? If you wish to try the beta: https://testflight.apple.com/join/1AlPbnLZ

No issue here since using the beta app

**Comment by ShadowRep** [comment]
I  got this today in the log:

> Logger: homeassistant.components.mobile_app.notify
Source: components/mobile_app/notify.py:198
integration: Mobile App (documentation, issues)
First occurred: April 1, 2024 at 13:30:44 (1 occurrences)
Last logged: April 1, 2024 at 13:30:44
>
>Internal error encountered. This message is generated externally to Home Assistant.

Never had that before.

Have not tried the beta, yet.

**Comment by alexsaas** [comment]
[No issue here since using the beta app]()

Thank you for testing it! Because of a medical incident in the family, I won't be able to test it today. 😳

**Comment by erkr** [comment]
For me, this issue is already happening intermittently for months, but with the latest store version it became kind of structural

**Comment by bgoncal** [comment]
> For me, this issue is already happening intermittently for months, but with the latest store version it became kind of structural

Can you check the beta?

**Comment by erkr** [comment]
Just installed the beta, let's see

**Comment by iloveicedgreentea** [comment]
I also had this issue recently and the testflight version seems to have fixed it

**Comment by dnlrsr** [comment]
TestFlight version seems to fix it.

**Comment by alexsaas** [comment]
Many thanks to everyone who has already tested it. Because I am currently unable to do so for the reasons mentioned.

**Comment by bgoncal** [comment]
Feel free to reopen this issue if needed

**Comment by alexsaas** [comment]
Sorry but wouldn't it be better to close the topic if the error is also fixed with the official store app? The beta as a solution cannot be final.

**Comment by bgoncal** [comment]
> Sorry but wouldn't it be better to close the topic if the error is also fixed with the official store app? The beta as a solution cannot be final.

It's not final, I'm preparing the release, but sure, let's keep it open, no problem

**Comment by alexsaas** [comment]
Sorry but wouldn't it be better to close the topic if the error is also fixed with the official store app? The beta as a solution cannot be final.

**Comment by alexsaas** [comment]
Okay thank you very much. Then I misunderstood.

**Comment by iStehle** [comment]
(io.robbie.HomeAssistant; build:2024.624; iOS 17.4.1) Mobile/HomeAssistant, like Safari): Disconnected: Did not receive auth message within 10 seconds
I am still suffering with this problem, only with the local connection. If I turn my WiFi off I can use the App. Same problem with safari. Loading then can not load screen.

**Comment by bgoncal** [comment]
> (io.robbie.HomeAssistant; build:2024.624; iOS 17.4.1) Mobile/HomeAssistant, like Safari): Disconnected: Did not receive auth message within 10 seconds
> 
> I am still suffering with this problem, only with the local connection. If I turn my WiFi off I can use the App. Same problem with safari. Loading then can not load screen.

In that case, since you also see the problem in Safari, it's not app-specific, so you probably need to ask some help for our friends from https://github.com/home-assistant/core

**Comment by erkr** [comment]
I had these errors a few times per day for months. Latest store version elevated it to several events per hour. 
For me there hast been a single event in 3 days with the current beta. So it definitely is much better 👌

**Comment by titis14** [comment]
Hello, I also have this error and in addition the Apple Car Play my action no longer works, no reaction and HA ends up closing on my Apple Car Play screen.

**Comment by dnlrsr** [comment]
Apple Car Play also uses the app as interface to access ha host. The TestFlight Version also fixes Apple Car Play.
________________________________

**Comment by alexsaas** [comment]
@bgoncal 

The new App Store version has fixed the error. Thank you. Good job!

**Comment by linwiz** [comment]
> (io.robbie.HomeAssistant; build:2024.624; iOS 17.4.1) Mobile/HomeAssistant, like Safari): Disconnected: Did not receive auth message within 10 seconds I am still suffering with this problem, only with the local connection. If I turn my WiFi off I can use the App. Same problem with safari. Loading then can not load screen.

I hope I'm not out of line for updating this, but I'm looking for more information. I suspect I am experiencing the same issue as you, in the App Store iOS app (2024.624) and the TestFlight app (2024.660), and Safari on iPhone as well as Safari on Mac. I am able to use HA locally (on host machine) on a web browser. Were you able to solve this @iStehle ?

**Comment by erkr** [comment]
Just reserve a fixed address in your router is enough. HA can remain default on DHCP

**Comment by MichaelMichaelMichaelMichaelMichael** [comment]
After the recent updates (`Core
2024.7.0
Supervisor
2024.06.2
Operating System
12.4
Frontend
20240703.0`) I have the same issue as described above.

**Comment by Christos977** [comment]
Also running into the same issue on core 2024.8.2/ Supervisor 2024.08.0. I can login to HA remotely for 10-15 seconds before it starts reconnecting and i see the following in my log viewer "2024-08-25 23:03:57.699 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [xxxxxxxxxxxxxxxxxxx] from 127.0.0.1 (Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/xxx.x.xxxx.xx Mobile/15E148 Safari/604.1): Disconnected: Did not receive auth message within 10 seconds.

Mine works fine via IOS and PC when connected to WIFI, this is only applicable when connecting remotely. I have tried testflight app and also removed static IP.

**Comment by RobotTheMLG** [comment]
I am also experiencing this issue on Core 2024.8.3 / Supervisor 2024.08.0. I have not tried the testflight app, but I have static IP disabled in the settings.

**Comment by ATFieldBeast** [comment]
I am also experiencing this issue on Core 2024.10.3 / Supervisor 2024.10.2.

At first, I thought that was my wireguard vpn's problem.
because when I use the URL which from my nginx，the remote connect works well both chrome and app;

When I use the wireguard to connect with my local network(that can let me use local ip to open my router page and other service page and works well), can use the chrome to open ha login page and submit my account to login, but then it turns to this issue's page such as: "loading data failed, retry...", and open the app it go through this issue's page.

Before today I just thought that is because the wireguard connect has no webSocket, but today, I use my laptop open the ha page through the wireguard, it works fine! It can open the page, can login well and can turns to the homepage correctly!

So now I think this is the problem with IOS?

**Comment by Ragetti13** [comment]
Hi,

This issue seems to be re-appearing (for me) with the following logs:

`Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/http.py:525
integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 22 November 2024 at 17:09:31 (5 occurrences)
Last logged: 23 November 2024 at 14:55:48

[546275103152] from 10.0.1.16 (Home Assistant/2024.11 (io.robbie.HomeAssistant; build:2024.971; iOS 18.2.0)): Disconnected: Did not receive auth message within 10 seconds
[546273668128] James Dean from 10.0.1.59 (Mozilla/5.0 (iPhone; CPU iPhone OS 18_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2024.11 (io.robbie.HomeAssistant; build:2024.971; iOS 18.2.0) Mobile/HomeAssistant, like Safari): Disconnected: Received non-Text message.
[546273667984] James Dean from 10.0.1.59 (Home Assistant/2024.11 (io.robbie.HomeAssistant; build:2024.971; iOS 18.2.0)): Disconnected: Received non-Text message.
[546456368848] Dawn Brown from 10.0.1.67 (Home Assistant/2024.9.4 (io.robbie.HomeAssistant; build:2024.905; iOS 17.6.1)): Disconnected: Received non-Text message.
[546177725584] Dawn Brown from 10.0.1.67 (Mozilla/5.0 (iPhone; CPU iPhone OS 17_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2024.9.4 (io.robbie.HomeAssistant; build:2024.905; iOS 17.6.1) Mobile/HomeAssistant, like Safari): Disconnected: Received non-Text message.`

I am running 2024.11.3 on an HA Yellow and the beta of the iOS app Version: 2024.11 (2024.976)


The loading spinning wheel only happens locally - access via external URL does not cause any issues.

**Comment by SmartElec** [comment]
使用浏览器也出现相同的问题，换台电脑就可以登录，或者更换域名也可以登录.本地无任何反向代理.

**Comment by iStehle** [comment]
For me it was an Application Firewall in my iOS that caused the issue. Http Proxy in there was not a good idea

**Comment by alexsaas** [comment]
No firewall for me. And yet it sometimes happens again. Yesterday after the update to 2025.3.2 even on the Mac with Safari. 

Now, however, only in the case of prolonged inactivity, e.g. if you have opened a new tab and read something elsewhere and come back. Or change the app via the app switcher and return.

**Comment by SmartElec** [comment]
最近使用浏览器访问经常出问题。使用浏览器隐私模式或者出现问题的时候打开浏览器调试模式删除应用存储数据，清除后就可以了。

**Comment by johntdyer** [comment]
Any way this error could include the device name ?  I have many mobile devices, probably 15 in total amongst the family and tracking down the culprit can be a bit of a PITA without this information
