### ISSUE TITLE
Watch complication icons are incorrect size

### ISSUE THREAD

**Issue by steve28** [home-assistant/iOS#276]
The watch complication icons for the infograph watch watch face are incorrectly scaled and get clipped.  See screenshot below:

<img width="545" alt="Screen Shot 2019-04-17 at 7 12 37 PM" src="https://user-images.githubusercontent.com/5874433/56332689-349fbe80-6146-11e9-8ca7-7c5be94ed02e.png">

I

**Comment by robbiet480** [comment]
https://github.com/home-assistant/home-assistant-iOS/blob/new-ios12/HomeAssistant/Utilities/CLKComplication+Strings.swift#L995

![](https://cdn.discordapp.com/attachments/551871772484698112/568270756514103306/unknown.png)

Seems Apple recently added a `(masked to circle)` annotation for the Graphic Circular Image sizes in the [HIG](https://developer.apple.com/design/human-interface-guidelines/watchos/icons-and-images/complication-images/) which is probably why this happens. Will have to play with exact sizing soon.

**Comment by SeanPM5** [comment]
A development decision was made to delay Watch and Shortcuts support from the 2.0 app and re-implement them in version 2.1 as iOS 13 specific features. 

Not only will this allow 2.0 to be released very soon, but the nice improvements coming with iOS 13 will make the Watch and Shortcuts integration better and easier to use - it'll be worth the wait!

I've been asked to close all existing Watch and Shortcuts-related issues since things will be changing a bit. Stay tuned in the coming weeks.

**Comment by balonchiks** [comment]
guys, do you think the issue should be reopened? as it's been a while now and the icons are still scaled as shown in the 1st post..

**Comment by fireRoads** [comment]
Got the same problem on HA 115.3, iPhone XS on iOS 13 and Apple Watch Series 6 on latest version. I guess you will work on this now again since this issue seems to be reopened?
