### ISSUE TITLE
Translation of states and description of entities provided by the app

### ISSUE THREAD

**Issue by Tobbe82** [home-assistant/iOS#2833]
Can't find a way in Lokalise to translate the states and description of the entities provided byt the app.

For example Floors Ascended, Geocoded location, Stationary, Not charging and so on..

**Comment by bgoncal** [comment]
I don't think this should be translated in the App level because lets say today you use your phone in English and after a few days you put it in Spanish.
- Automations around it will fail
- Your history will be confuse

After reading [this](https://developers.home-assistant.io/blog/2022/12/01/entity_translations/) perhaps these translations could come from the Mobile App integration

**Comment by Tobbe82** [comment]
Sorry, I was unsure of exactly where to post this. Thought of it as something connected to the app. 

But the keys that should be translated needs to be posted somewhere at lokalise 😅 and put to use in the frontend.

**Comment by bgoncal** [comment]
Yup, code changes are needed, want to open a PR for it? otherwise I'll add it to the backlog.
Next time you can open a discussion in github or home assistant community instead of github issue, in here we track only bugs
