### ISSUE TITLE
2024.7: black bar at top

### ISSUE THREAD

**Issue by bcutter** [home-assistant/iOS#2873]
**iOS device model, version and app version**

Model Name: Various (with and without nodge)
Software Version: 15, 16, 17
App version: 2024.7

**Home Assistant Core Version**
2023.10.5

**Describe the bug**
Since todays 2024.7 companion app update there's a significant black bar at the top. Tested on 3 iPhones. No matter if light or dark mode is active.

TBH I don't even remember what it looked before, but the fact it somehow disturbs me in a way I immediately noticed it, motivated me to raise an issue here.

Does not exist in Safari on the same iPhones.

**To Reproduce**
Update to 2024.7

**Expected behavior**
The way it looked before.

**Screenshots**
![image](https://github.com/user-attachments/assets/597c4db3-1e4c-4849-80e6-ab332d1ef54f)

![image](https://github.com/user-attachments/assets/10162672-5448-40ad-a8ba-80d8a20764e5)

**Additional context**
I don't have another iDevice with an older version because all got updated today.

**Comment by bgoncal** [comment]
Hi, looking at your HA core version, I believe that’s the issue, 2024.7 brings a change that aligns the color variable used between web and app. Please update your Home assistant server

**Comment by bcutter** [comment]
What should it look like (with a recent HA Core version)?

**Comment by bgoncal** [comment]
![image](https://github.com/user-attachments/assets/9cf82a18-37d4-4b04-b66d-4267179e9790)

**Comment by unconnected** [comment]
Having the same issue on my iphone 12 pro. It used to be a blue bar on top, now it’s black. Weird if it should be alligned with the web version of Hassio, because that one is blue in Safari.

App:

![IMG_5569](https://github.com/user-attachments/assets/85d1776b-ee9d-455e-94dd-4debbe473cd8)

Safari:

![IMG_5568](https://github.com/user-attachments/assets/4af82f76-31e0-41ee-870d-2588ff90680b)

**Comment by bgoncal** [comment]
What’s your HA version?
Frontend has a different logic to tint the browser status bar, if you want it to be tinted in the newest version of the App, please also update core

**Comment by bgoncal** [comment]
More details on what's changed in this PR: https://github.com/home-assistant/iOS/pull/2827

**Comment by unconnected** [comment]
> What’s your HA version? Frontend has a different logic to tint the browser status bar, if you want it to be tinted in the newest version of the App, please also update core

Almost afraid to say, but I'm still on 2023.2, the last one that didn't need the python upgrade on my Raspberry PI (which didn't have that Python version available at the time). I need to update everything but I need some time to do so :/

Is there a color we can set in the current theme somewhere which is used by the App?

**Comment by unconnected** [comment]
If you don't want to upgrade your hassio core (or can't yet), make sure this line is in your configuration.yaml:

```
pi@raspberrypi:/home/homeassistant/.homeassistant $ head configuration.yaml

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
```

Then create a file in the themes folder (and create the folder if it doesn't exist yet):

```
pi@raspberrypi:/home/homeassistant/.homeassistant $ cat themes/app_header_theme.yaml
app_header_theme:
   app-theme-color: "#03a9f4"
   app-header-background-color: "#03a9f4"
pi@raspberrypi:/home/homeassistant/.homeassistant $
```

And restart your hassio instance. After doing that, select the 'app_header_theme' in your profile:

![image](https://github.com/user-attachments/assets/4de5db45-c2e8-4cbb-ae2b-4864944b9f0f)

And the bar on top is blue again. Or whatever color you want. Think the issue can be closed because it is not a bug, although the new IOS code could have had a fallback to app-theme-color as it was previously :)

**Comment by bcutter** [comment]
> although the new IOS code could have had a fallback to app-theme-color as it was previously :)

Exactly 👍🏼

This way this update wouldn't have contained this "breaking change".

It takes weeks for some users to update their HA instances to 2024.7.

But I think that fallback can still be implemented, right? 😀

**Comment by bgoncal** [comment]
@bcutter @unconnected any of you tested the beta to see if the fix worked for your HA instances?

**Comment by bcutter** [comment]
Not a test flight user.

**Comment by bgoncal** [comment]
I just installed an old docker version of home assistant to try out the fix (previously I tested by not providing app-theme-color manually).
The fallback won't work, because the frontend provide "themeColors" to the app through javascript, and it was providing black color in older versions, so to fix that we would need to update frontend code which would lead to the user have to update home assistant anyways.

New fallback on apps side:
https://github.com/home-assistant/iOS/pull/2924

**Comment by unconnected** [comment]
I'm willing to test the beta if you want! I still have the 'theme fix' active but I can easily switch. Is there a way to get the beta on my device?

**Comment by bgoncal** [comment]
> I'm willing to test the beta if you want! I still have the 'theme fix' active but I can easily switch. Is there a way to get the beta on my device?

Yes, but the fix above is not available yet

https://testflight.apple.com/join/1AlPbnLZ
