### ISSUE TITLE
Cannot configure Lock Screen Widgets

### ISSUE THREAD

**Issue by AndreasBackx** [home-assistant/iOS#2973]
**iOS device model, version and app version**

Model Name: iPad Pro (11-inch) (3rd generation)
Software Version: 18.0 Public Beta (22A5350a)
App version: 2024.7 (2024.730) and 2024.8.1 (2024.791) (tested on both and exact same behaviour)

Model Name: iPhone 15 Pro
Software Version: 18.0 Public Beta (22A5350a)
App version: 2024.8.1 (2024.791)

**Home Assistant Core Version**

2024.8.3

**Describe the bug**
On iPadOS I can add a lock screen widget once and it works. But then I am unable of editing it and the configuration is not saved.

On iOS I cannot edit a lock screen widget when adding it.

**To Reproduce**
See attached video.

**Expected behavior**
On iPad for the lock screen widgets to remember the configuration and allow changing it after first configuration.

On iPhone to allow configuration.

**~~Screenshots~~ Screen recordings**

iPad (was too large for GitHub): https://imgur.com/LTmu7Uf

iPhone: https://github.com/user-attachments/assets/6965657a-8ad2-4d71-af42-7bf4d85683c8

**Comment by AndreasBackx** [comment]
cc @literally-anything considering you recently added it in #2830 and you might know what is the cause.

**Comment by AndreasBackx** [comment]
Can confirm it's not an iOS 18 issue. I see the same behaviour on another iPhone with iOS 17.6.1.

**Comment by bgoncal** [comment]
Thats unfortunately not under HA App control, it's an iOS bug, what I noticed with my widgets is that if you wait a few minutes, it will "save" the value. Give it a try and let me know, for now I'll be closing the issue since it's not up to HA App to fix.

**Comment by bgoncal** [comment]
Sorry I missed the second issue related to iPhone, high chance it is also related to iOS, just a bit more information, that "configuration popup" you see is entirely made by Apple, we don't have code to launch it or close it, we just make the fields available (parameters).
Since this form does not have dynamic values (such as a list of scripts, a list of assist pipelines), it is just a plain form.

Try rebooting your phone, it usually helps with widgets glitches.

Also, apparently if you save your lock screen it persists the value the next time you try to add it:

https://github.com/user-attachments/assets/495ee57e-b3a5-4ff7-8c82-e92e804f65c3
