### ISSUE TITLE
Location inaccurate

### ISSUE THREAD

**Issue by lancelon** [home-assistant/iOS#298]
Firstly, THANK YOU ROBBIEE!

Secondly, I'm still having issues with the iOS app location deciding I'm home when I'm not. I work 150m away from home. Life360 can cope with this and never decides I'm at home when I'm not. The iOS app has consistently decided that "meh, close enough!" and placed me at home when I'm at work. I'm on beta 2.0.0 build 44.

My work zone is set to a 50m radius and so is my home.

**Comment by robbiet480** [comment]
You'll need to provide some specific details for me. As a start, can you provide me the accuracy attribute of the `device_tracker` when it incorrectly updates to the wrong zone? Also, please provide the sensor value of Last Update Trigger.

**Comment by lancelon** [comment]
Hi Robbie

So the iOS app decided I arrived at home at 12:30 as far as I can tell. I didn't actually leave work until 12:40. This is the information HA has in the dev view:-

source_type: gps
latitude: xx.951019
longitude: -xx.082998
gps_accuracy: 50
battery: 15
friendly_name: mydevice

Currently (this is 1hr 15 mins later), the app still thinks my battery level is wrong, and the device hasn't noticed that I have moved back to work, something I did half an hour ago. All the while Life360 has kept up with my movements perfectly.

I'm not moaning - what you've achieved with the app is amazing - I'm just mentioning it in case my situation (having work and home relatively close but not ridiculously close) is an outlier and you would otherwise never hear of it! :-)

THANKS

**Comment by Swiftnesses** [comment]
Using V1 of the iOS app my location was always spot on (with regards zones), it now leaves zones and moves hundreds of metres away from the house, triggering flows...

**Comment by Swiftnesses** [comment]
Example (whilst home):

```
source_type: gps
latitude: XXX
longitude: XXX
gps_accuracy: 2235
battery: 64
altitude: 67
vertical_accuracy: 10
friendly_name: XXX
```

**Comment by gieljnssns** [comment]
I'm having the same problem.
My phone also leaves the house.
![Schermafbeelding 2019-05-31 om 20 36 32](https://user-images.githubusercontent.com/17234951/58727199-f56eb980-83e3-11e9-8499-0a17c8971a7c.png)

On that moment the gps_accuracy is very high
![Schermafbeelding 2019-05-31 om 20 27 23](https://user-images.githubusercontent.com/17234951/58727079-a32d9880-83e3-11e9-9303-41b4a3da9287.png)

In the beta app the trigger was background_fetch
in the appstore version was the trigger 30

**Comment by robbiet480** [comment]
We determined that @gieljnssns location was coming from a cell tower which gives a hardcoded accuracy of 1414m. Unsure how to filter this kind of "bad" data out, since its not actually bad, just higher accuracy.

@Swiftnesses I need to know what is triggering the zone leave/enter events. Is it actually a region event or is it something like a SLU. How close is your work to your home? Within maybe 3 km? It's up to iOS to determine when you enter/leave a zone, it can sometimes do that by looking at cell towers near to a zone, so if you don't travel far for work from your home it may confuse what towers are close to what zones. Please join me on Discord in #ios in the next few days so I can debug hands on with you.

@lancelon Similar questions for you, although I know how far your work is from home... What is triggering the update? Is it actually a region enter/exit or a SLU? You can look at the last update trigger sensor to know. Correlate the update time of that sensor to when you jump in/out of zones. Location code only improved in 2.0, so 1.5 may have just had bad code that was masking the problems that you are now seeing due to not always updating properly. You may want to get some iBeacons and attach them to the zones in order to make iOS only trigger region enter/exit based on the beacon(s) visibility.

**Comment by scstraus** [comment]
I'm having similar issues with 2.0 when 1.5 worked near perfectly. It often takes hours to realize I'm home, whereas it used to be instant.

**Comment by Martinvdm** [comment]
Same issue. The accuracy of the gps is a lot less in 2.0 app then in 1.5 app. Often it takes a long time to leave a zone or enter a zone.

**Comment by scstraus** [comment]
Here are the attributes of my wife's device tracker which arrived home and connected to my WiFi 16 hours ago but still shows as being 4 minutes away from the house.


  | source_type: gps battery_level: 84 latitude: 50.037993581851545 longitude: 14.38860049019642 gps_accuracy: 165 altitude: 263 vertical_accuracy: 11 friendly_name: Alena's iPhone Location
-- | --

**Comment by scstraus** [comment]
Above example may have had something to do with her being on airplane mode part of that time, but here's one from my phone where it's showing me 1km away despite being in the home zone for last 15 minutes. Definitely connected to wifi and in a zone that worked perfectly under v1 for more than a year.

```
source_type: gps
battery_level: 95
gps_accuracy: 65
altitude: 200
vertical_accuracy: 10
```

**Comment by fouram** [comment]
I'd just like to chime in here and update with that fact that this is still happening. My wife works about 4 miles away (well outside "Home" zone which is set to 20m) and her device still shows she is at home with 100% battery and "charging" even though she left the house (and the home zone) twice over 8 hours ago (and is still gone). I'm not sure what to do to get the app to respond but it seems iOS is deciding that these location updates are not important and is just outright ignoring them. If she opens the app it will update, but she's not a techie person so she doesn't use it much yet (and convincing her is becoming difficult with the way this appears to be misbehaving)

**Comment by scstraus** [comment]
Yes me too. It still misses a large percentage of updates which the 1.5 app did not.

**Comment by lancelon** [comment]
Same problem here. It's totally useless (I don't mean that nastily) as a location tracker for me, it only updates sporadically, and even then, the update is often wrong. But I think @robbiet480  has moved onto the Android app now?

**Comment by roflmao** [comment]
I created a sensor based on the attribute gps_accuracy for me and the wifey:

[https://www.jottacloud.com/s/006d557e5a6f6444881974b32b74e819ea1](url)

We both run the latest from the appstore.

**Comment by KennethLavrsen** [comment]
Hi I commented on a similar bug report a week or so ago and the issues were closed.

But the issues are still there.

The phone reports locations that are totally off the real position and always with an accuracy of kilometers

This used to be so reliable. Now it is useless. My alarm system gets turned off again and again while I am at work when it happens that the bogus location and its mega area overlaps my home. I have no other choice now then disable IOS app as device tracker.

See below image. The arrow is where I am. And the bug circle with a K is where the app reports me to be.



![image](https://user-images.githubusercontent.com/8373419/86771747-10821300-c053-11ea-9dff-2cf3f47fac07.png)


and then 5 minutes later. I have not moved from my chair. And the location has jumped several kilometers south.

![image](https://user-images.githubusercontent.com/8373419/86771914-50e19100-c053-11ea-8774-c3ba0ec7082c.png)

The location data have become garbage

**Comment by KennethLavrsen** [comment]
Here a few minutes later and I am at work with good accuracy as I am supposed to. And still I did not get out of my chair.

![image](https://user-images.githubusercontent.com/8373419/86772665-bb470100-c054-11ea-80bb-913654e0a5bd.png)

**Comment by lancelon** [comment]
I've given up trying to get this fixed - sadly I just use life360 now

**Comment by KennethLavrsen** [comment]
Some more follow up.

As I am sitting here I am seeing the jumping in positions again. And again it jumps to the exact same bogus positions as earlier today

Here are the data from the device tracker entity as Home Assistant see it

Good position

```
source_type: gps
battery_level: 88
latitude: 55.663330078125
longitude: 12.396366329403612
gps_accuracy: 65
altitude: 10.2988862991333
vertical_accuracy: 10
friendly_name: Kenneth's iPhone 7
```


Bad position

```
source_type: gps
battery_level: 85
latitude: 55.641326904296875
longitude: 12.412471422929828
gps_accuracy: 2500
altitude: 10
course: 0
speed: 0
vertical_accuracy: 10
friendly_name: Kenneth's iPhone 7
```

Note the accuracy number 2500!!!    That is 2.5 kilometers. if the app would just stop reporting position when the accuracy is very poor then a lot of the problem would be gone. It does report location when I move around. The problem is these garbage positions that overlap the zones where I work and where I live.

**Comment by lancelon** [comment]
Agreed. I haven't understood whether Robbie is still actively developing or not or whether someone else has taken over the job?

**Comment by TomBrien** [comment]
@KennethLavrsen quickly checking street view at those coordinates shows that there is a cell tower there. When a significant location change is triggered by a cell tower change it seems iOS is now reporting the tower location.

@zacwest can we perhaps use the cell tower change/RegionMonitor waking the app to trigger a a proper GPS location via the OneShot?

**Comment by lancelon** [comment]
@TomBrien  "iOS is now reporting the tower location."

This makes kind of sense - so iOS/the app is reporting the CELL TOWER location not the phone's location? This helps make sense of Robbie's  post from the 18th of June last year  - at the time I didn't have a clue what he meant by  "We determined that @gieljnssns location was coming from a cell tower which gives a hardcoded accuracy of 1414m. Unsure how to filter this kind of "bad" data out, since its not actually bad, just higher accuracy." because it just didn't seem to make any sense. It still doesn't. But if @gieljnssns data wasn't reporting HIS location but the location of a cell tower then....I get it?

**Comment by TomBrien** [comment]
Yep I think this is another iteration of that. I'm not sure if my proposal above will work (not sure how much we can do on a wake up in this case) but would be better to try and get an actual fix, it seems that iOS is no longer giving a _special_ number for the accuracy

**Comment by zacwest** [comment]
> can we perhaps use the cell tower change/RegionMonitor waking the app to trigger a proper GPS location via the OneShot?

This is what "In-Development Updating" does in 2020.3+ and by default in 2020.4+.

**Comment by KennethLavrsen** [comment]
This map shows my area
The star is where I am (Motorola Solutions office in Glostrup, Denmark).
The two red dots are the bogus positions.
The dark dots are cell towers (this is from the official government cell tower database).
As you can see there are many towers that are more near me. I have LTE coverage where I am. The southern of the two bogus positions are at a Motorway and not that far is a cell tower. But the northern bogus position is in a green park/forest area with no cell tower near.  The thing I noted is that the wrong position is always sent with a huge accuracy circle. It is probably a problem in the latest IOS versions but if the app is changed so it never reports a position change if the accuracy is worse (larger than) 1000 meters or so, we may be able to simply filter the noise away. It also needs to ignore these data points when it decides to enter or leave zones.

**Comment by KennethLavrsen** [comment]
Today I had to stop using the app for location. Every day for two weeks my alarm system turns off because the IOS app reports its location with the wrong coordinates and 2.5 kilometer accuracy. 2.5 km is the radius of the circle. The area is almost 20 sq kilometers. That is the entire city of Glostrup. It is totally useless.

**Comment by JasonRS1969** [comment]
This switching of locations is happening several times per day for me too, and it's putting my location consistently as 2 miles in a straight line from my actual location.

4 times today it's put me in the same location when the phone hasn't physically moved (sat on its charger) and triggered exit automations.

**Comment by TomBrien** [comment]
@JasonRS1969 what is the reported accuracy of those location updates? Is it 1414 m? If you check that location on a satellite view is their a cell tower there?

**Comment by JasonRS1969** [comment]
In the log I see "ignoring one shot location with accuracy over threshold"

Then some have Accuracy: 1415.0M and others have Accuracy: 2500.0M

The location it's placing me at is 3300M away, in a straight line.

**Comment by KennethLavrsen** [comment]
I had this 2500 meter, always in the same wrong location several kilometers from me. I then installed Owntracks and saw it reporting the exact sane to the millimeter. Then I made a full power down of the phone and started it up again and since then the problem is gone. I think something goofy happened after last ios update. Try a power cycle so you reboot the phone from cold. I did this more than a week ago and the problem has not come back.

**Comment by zacwest** [comment]
I believe many location issues have been resolved since this ticket, and if there are any existing ones please open a new ticket. There's a new Location History in the app's settings under Location which has a share button which provides an image of the location update and all the debug information necessary to try and figure out the bug. You don't need to attach the raw location data to the ticket, but hopping in Discord may be the easier route to getting it fixed.

**Comment by scstraus** [comment]
I have noticed that location has been better behaved recently. At least it's been wrong in consistently the same way so that I could redraw my zones to solve it.

**Comment by lancelon** [comment]
Don’t punish yourself - use the iCloud3 integration (Gary Cobb)
