### ISSUE TITLE
Geocoded location option to show zone (if inside)

### ISSUE THREAD

**Issue by Swiftnesses** [home-assistant/iOS#347]
I previously used the geocode component (https://github.com/michaelmcarthur/GoogleGeocode-HASS) which has an option to replace / insert the geocoded location with the zone name, could this be added?

**Comment by SeanPM5** [comment]
I think this is a great suggestion.

Since the whole point of geocoded sensor is to display coordinates in a more friendly way, it would make sense to simply display the zone name (if inside one) rather than "1234 Main Street, NY."

Might be useful to expose the current zone as an attribute of the geocoded location sensor too if possible.

**Comment by TomBrien** [comment]
I know in the code there is a comment about using the native [MapKit Placemark](https://developer.apple.com/documentation/mapkit/mkplacemark) (and then the code uses [CLPlacemark](https://developer.apple.com/documentation/corelocation/clgeocoder) to do the reverse geocode) so this may require something of a change of methodology.

https://github.com/home-assistant/home-assistant-iOS/blob/master/Intents/SendLocation.swift#L104

**Comment by robbiet480** [comment]
While possible, this will take quite a bit of rework as the geocode sensor we have right now doesn't have a way to get the zone that we are currently in. Expect this later in 2.0, if not 2.0.X build after release.
