### ISSUE TITLE
Cannot connect when TLS-Clientcertificate is requested

### ISSUE THREAD

**Issue by unconfigured** [home-assistant/iOS#380]
The app is currently failing the on-boarding when the server requests a client certificate. To request a certificate does not automatically mean it is required. I've a TLS listener on my webserver that has multiple vhosts. That server has a single TLS configuration always asking for a client certificate and proceed if none is provided ("request" but not "require"). The vhost config there after decides, if a client certificate is required for this particular destination, or if it's a vhost that can proceed without certificate. This is quite common I think. Can you please try to continue connecting without a client certificate as before? Would be awesome :)

Latest tested version: 2.0.0 (58)

**Comment by robbiet480** [comment]
I understand how this would be annoying. The issue is that iOS doesn't differentiate between a client certificate being requested and one being required. My suggestion for the moment would be to temporarily disable the client certificate request to get through onboarding and then re-enable it. I can try to implement logic at some point to only fail onboarding if it's been requested more than once but it's not high priority for me at the moment.
