### ISSUE TITLE
Google oAuth support

### ISSUE THREAD

**Issue by Warstomper** [home-assistant/iOS#389]
I have been trying to secure my various webapps (like home assistant) using [https://github.com/vouch/vouch-proxy](url). Mostly, this is working fine fom browsers, however, I can't seem to get it to work with the HA app (I am running the latest beta). The error mentioned in the following article is observed:

https://blog.cloudrail.com/solving-disallowed_useragent-for-google-services/

From my limited knowledge, I understand that the User Agent being used by the app is basically blacklisted by google for these kinds of authentications and it could be only a matter of changing the uer-agent as mentioned here:

https://stackoverflow.com/questions/40591090/403-error-thats-an-error-error-disallowed-useragent

Would this be something that's possible to add/support?

Thanks a lot in advance.

**Comment by torarnv** [comment]
@Warstomper Do you get HA beta to even open a webview for the auth? I tried doing something similar with Cloudflare Access, and the HA app doesn't have any logic to trigger an auth screen as far as I've learned.

**Comment by Warstomper** [comment]
I got to the point where it loaded the google error message as seen in the linked blogpost atleast, as I let nginx first force the auth via a 302 redirect.

**Comment by robbiet480** [comment]
@torarnv May be able to provide a update on this one. Turns out there was a implementation issue with HA front end which I believe he has already gotten a fix merged for?

**Comment by torarnv** [comment]
Actually this issue is due to Google not allowing just any user-agent to do the oauth flow. The HA issue i fixed in the frontend was after oauth successfully completed. I got around this issue by overriding the user-agent:

```swift
self.webView.customUserAgent = "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36"
```

Since WKWebView doesn't allow custom headers for subresource requests this was the only option. 

I now have a mix of:

  - Setting custom headers for the Alamofire session used for verifying the connection when onboarding
  - Authenticating normally via the web flow for the ASWebAuthenticationSession when onboarding
  - Setting custom headers for the Alamofire session used for API requests
  - Setting custom headers for the Alamofire session used for webhooks
  - Authenticating normally via the web flow in the WKWebView used for the UI, after overriding the user-agent

**Comment by hyperbolic2346** [comment]
Just ran into this issue as well. Trying to use google oauth via 302 redirect on my nginx ingress.
