### ISSUE TITLE
Hide status (top) bar

### ISSUE THREAD

**Issue by newlund** [home-assistant/iOS#405]
Would it be possible to add an option to hide the status (top) bar?
I read somewhere that it might already be there but can't find it. Perhaps it was referring to the bottom bar that I have already removed?

**Comment by newlund** [comment]
https://www.tutorialspoint.com/how-to-hide-the-status-bar-in-a-ios-app-using-swift

https://developer.apple.com/documentation/uikit/uiviewcontroller/1621440-prefersstatusbarhidden

**Comment by robbiet480** [comment]
Sure, it's possible, but may I ask why? I don't know if you are using 1.5 or 2.0, but in 2.0 there is support for theming the top bar automatically to match your frontend theme colors. If your issue isn't with the colors, then I assume you just want to hide the clock and other information?

**Comment by newlund** [comment]
I'm using the 2.0 beta. Thanks, did not know I could theme the top bar. I will try this in order to get a more uniform look.
However, I would really like if I could hide the bar. I don't need the clock since I have it in lovelace and by removing it I would have room for an other row of sensor data without scrolling.

Thanks!

**Comment by 0x00-0xFF** [comment]
Just to make my request more clear. I'm using the companion app on my iPad as a home controller (see enclosed image). I think this would look a lot better to have the app-status-bar removed, so we're not having the color issue and have a bit more space on the screen. 

![Untitled](https://user-images.githubusercontent.com/7880448/67566559-6498d180-f728-11e9-88b3-b3417a0095cf.png)

**Comment by 0x00-0xFF** [comment]
Theming doesn't work for me, when changing the primary-color and executing a frontend.reload_themes I see the reload_themes websocket call and the themes_updated event, the theme changes on my iOS instances, but the statusbar stays blue.

**Comment by TomBrien** [comment]
Are you specifying you’re colour values as hex values? [see here](https://companion.home-assistant.io/en/troubleshooting/setup.html#the-ios-status-bar-top-bar-with-cellwi-fi-strength-does-not-match-my-theme).

**Comment by 0x00-0xFF** [comment]
No, until now. But the status bar stays blue, only the header bar color is updated.
Maybe I should post a new issue instead of hijacking this issue.

**Comment by mountainsandcode** [comment]
Can you check with the latest App version? That should have fixed the status bar coloring

**Comment by DavyHubrecht** [comment]
Seems to be fixed after the update. Thanks!

**Comment by skynet01** [comment]
I also use the app on my ipad that's mounted on the wall and even though i can theme it and match the color i don't need to see battery and clock of my iPad (that's always charged). Would be amazing to have an option to hide it completely.

**Comment by ee02217** [comment]
Not sure if this could be an option, but it would make my grid card in panel mode fit perfectly when hiding the menu and the navigation bar.
Otherwise there is just those 3 millimetres of scrolling. Hehehehe

**Comment by pixeron** [comment]
Cant believe that such a simple fix was never implemented. This top bar looks so out of place.

**Comment by skynet01** [comment]
Yes can this be added pretty pleaseeeee

**Comment by zacwest** [comment]
The issue here is that modern devices have notches and areas where the content can't really show through. Disabling the status bar on a non-FaceID iPad is likely possible, but how do we handle this on the newer ones?

The top header area of the frontend doesn't support underlapping the status bar, so we can't simply turn it off or the contents will go under the notch.

**Comment by sylviepipi** [comment]
I use browser_mod to turn the screen black when nobody is in the room. But i always see the bar. Why not add an option so user can choose to show/hide it and by default keep it on for the persons having a notch ?

**Comment by thanksmister** [comment]
@zacwest maybe you are not taking into account the many users that use home assistant app on iPads or as dedicated mounted applications?   Do you have plans to supported wall mounted iOS or Android devices?    I think for Android, users can use the  [WallPanel](https://github.com/thanksmister/wallpanel-android) application or Fully Kiosk, but there is no current solution for wall mounted iOS devices.   I am working on a version of WallPanel for iOS but I am hesitant because HA has more resources to create the same app.

**Comment by zacwest** [comment]
If you are interested enough in the feature to consider making an app for it, feel free to make a pull request here to add the functionality. If it makes sense and doesn't cause problems (e.g. only iPadOS or something to take into account the safe area issue s) I am not against adding it.

**Comment by thanksmister** [comment]
I would not do a PR on the current project because the project is not designed to run on tablets or full screen for dedicated IoT devices, it’s built for mobile devices.

I believe users that would want full screen are trying to run the app as a dedicated wall mounted device, it does not make sense to run the HA companion as a dedicated tablet or screen for HA.  You can’t really run it as a kiosk app for iOS, it requires additional features.

It makes better sense to make a separate application that authenticates with HA but does kiosk mode with motion or face detection for waking the device and works motor as an always on app.

My concerns are that the HA mobile API doesn’t support push notifications for 3rd party apps.  The mobile APIs also seems to be for the mobile companion app and not for a dedicated wall mounted device.  Lastly, I am not entirely sure HA wouldn’t just make a tablet or wall mounted version in the future, making my efforts futile.

For the mobile API I really don’t like the way you require a custom interface for the web view in order to authenticate with mobile devices and also the APIs for mobile are so closely coupled with companion app and not 3rd party developers.

A dedicated full screen app for example would mostly work on a users local network and not require many of the features of the mobile API.   I think using web sockets would be a better approach and more appropriate if users wanted to provision large number of tablets.

I would also think users would want to load specific dashboards and lock down the web pages so the end user cannot interact with the configuration.  

Anyways, my experience is building dedicated tablet apps for HA and this request for full screen seems to be asking to support a kiosk like app.   However the companion app would not be a good fit for this even if it offered full screen support.  There is a lot more required to support a good user experience.

**Comment by zacwest** [comment]
I don't believe there's anything inherently anti-kiosk in the iOS app, but it's definitely not a focus. If you think you can get better kiosk functionality in a separate app, you should feel free to make one. There's nothing in the [native app API](https://developers.home-assistant.io/docs/api/native-app-integration) which is restricted to official apps; you can implement your own with push support by specifying the push URL in the registration, and HA calls that URL with an HTTP request. If you want to look at writing a new app using the WebSocket API, I recommend using [HAKit](https://github.com/home-assistant/HAKit) which is what the app uses. At some point in the future it'll gain authentication support, but right now it does not have that built-in.

**Comment by sylviepipi** [comment]
We'll after using fully kiosk browser for a long time, my needs are covered by the mobile app with a full screen (and maybe an autoreload in case of error). I shorty tried Kiosk PRO which also works, but it's not open source and requires a license.
Anyway after learning how to code i'll look into the pull requests but i guess that will not be anytime soon so.

**Comment by skynet01** [comment]
I also used kiosk browser, kiosk pro and now the iOS app on 3 tablets around my house. The iOS app is perfectly fine for me and satisfies all the use cases. You can lock it down with user permissions and dedicated dashboard. You can send commands to it just like kiosk browser using Browser Mod and you can turn on accessibility mode on iPad so people can’t exit. I don’t think we need a new app. The only issue I have is this stupid status bar :)

**Comment by thanksmister** [comment]
@skynet01 but the documentation for kiosk browser says it hides the status bar?  https://scalefusion.com/ios-kiosk-browser.  Also, does kiosk browser offer a screensaver or wake device on motion, touch, or face detection?  It seems you would not want to run the device with the screen on or without a screensaver for long periods of time.

**Comment by skynet01** [comment]
[Kiosk Browser](https://play.google.com/store/apps/details?id=de.ozerov.fully&hl=en_US&gl=US) if only for Android devices and it's great for that. What you found is something else I never used. For iOS our only option is this companion app or some full-screen app like [Kiosk Mode for Ipad](https://apps.apple.com/us/app/kiosk-mode-for-ipad/id986554705) (it crashes often and seems to be pretty laggy). My iPad devices run without a screensaver for 6 months already without any issues. I do use Browser Mod to black the screens at night though... but you can see the status bar still .. yes face detection and wake on motion would be pretty cool but that sounds like separate tickets :)

**Comment by thanksmister** [comment]
@skynet01 ok, I understand, there is also the free version of WallPanel for Android that works well and has other features to help save the screen.  (https://github.com/thanksmister/wallpanel-android).   My thought was that we need a version of companion or wallpanel for iOS that has features like screensaver, wake on user present, etc.   I think having the device on all the time is not ideal.    I also assumed, maybe incorrectly, that people are asking for fullscreen mode with no status bar because they are trying to run companion on a wall mounted device.

**Comment by skynet01** [comment]
That's correct I run it on wall-mounted iPads around my house (
![image](https://user-images.githubusercontent.com/8117544/119394965-b77d9680-bc87-11eb-938f-35f8862538e6.png))
.  I don't think the motion detection and screen saver are absolutely needed. iPads use LCD screens so you don't have to worry about the burn-in issue (otherwise tv menus in restaurants would have screen savers). I have 2 iPads mounted in high traffic areas so they would be coming on and off all the time so I wouldn't even use that feature. In my bedroom, I would probably turn it on.
