### ISSUE TITLE
Remove Google Firebase dependency for notifications

### ISSUE THREAD

**Issue by mpeterson** [home-assistant/iOS#430]
Hi, I just started testing the beta version this week and one thing that stood out to me is that now notifications are dependant on Google's Firebase to enable push notifications. This dependency is a big no-no and saddens me if I have to stop using such a great application because of this.

I was wondering if there might be a possibility to change this in the future? Couldn't each HA instance push their own notifications without having the 3rd party requirement? 

It would be interesting if you could explain the reasoning behind this decision.

I don't want to sound unappreciative and that I'm taking your effort for granted. I find this app incredibly useful and this new version looks amazing! So I'm super happy to monetary contribute to it now that you started receiving donations for it :)

**Comment by mpeterson** [comment]
Moreover, if I go to disable it in Privacy, kill the app and open it again, the switch is enabled again.

**Comment by robbiet480** [comment]
Hi, I totally understand the annoyance of using Firebase. It wasn't exactly my first choice either. However, it's the only modern (read: full support for the very latest iOS 13 Apple Push Notification Service (APNS) features) and cross platform solution that isn't marketing focused entirely, like AWS Pinpoint is. In version 1 of the app we used AWS SNS and a bit of homegrown code but SNS has now stagnated and isn't expected to gain support for the new features in iOS 13 (one of which is actually required to be able to push notifications to the Apple Watch starting in watchOS 6).

The only alternative would've been building our own push infrastructure, including token registration, sending at high speeds, dealing with disabled devices and that's all just to get iOS and Apple Watch supported. It was too much work for me to take on.

I'm sorry to hear about the switch not working but I _believe_ it's because I required Firebase turned on for the beta because of the Crashlytics integration. I'll take a look for the 2.0 App Store release and make sure it works.
