### ISSUE TITLE
IOS 13 hass-browser_mod = music player

### ISSUE THREAD

**Issue by BrownC0de** [home-assistant/iOS#447]
Hey.
I apologize for bad English, it's all Google.

I use hass-browser_mod in it the browser is defined as a media player.*
And thus I can listen to music / radio. And everything worked fine on iOS 12. But after updating to iOS 13, in the background after 20 seconds, the perception is interrupted.
By the way, there is no such problem in the safari browser, playback continues both in minimized form and after the screen locks.

**Comment by SeanPM5** [comment]
Hi,

From what I understand, Apple has gotten a lot more strict about background tasks in iOS 13. They have lowered the background limit to just 30 seconds. See here: https://twitter.com/arekholko/status/1178700431867994113

Since Safari is a default system app, it's exempt from these limits and behaves differently. But third party apps will be limited to 30 second background tasks. I'm not sure that anything can be done to fix this unfortunately, since the limit is imposed by Apple on the operating system.

**Comment by Iv711** [comment]
I realized that it’s all about the changed Apple policy. But other non-system applications somehow circumvent these limitations. Maybe for the application Home-assistant there is a way out?
