### ISSUE TITLE
activity sensors return data in metric despite HA system unit setting

### ISSUE THREAD

**Issue by sqweak** [home-assistant/iOS#502]
Both sensor.distance and sensor.average_active_pace return their data in meters. It'd be great if these respected the HA config value for imperial/metric.

**Comment by robbiet480** [comment]
@balloob suggested that the way to implement this is not in the iOS app but in `mobile_app`. Mobile apps, such as the iOS app, should pass along a new value, `alternative_unit` which could be like `feet` if the value is in `meters`. Then it would be up to `mobile_app` to do the conversion.

This is low priority for me though.

**Comment by sqweak** [comment]
Not sure I see why the client app would need to pass anything. Since `mobile_app` has access to the config setting, knows that iOS is the source, and we know that iOS pedometer is in meters, why couldn't we just build it to do the conversion that matches config setting without change to the iOS app?

**Comment by robbiet480** [comment]
We (iOS app) needs to provide relevant units, not just the system. e.g. you want distance in feet, not inches, but HA isn’t smart enough to know that

**Comment by TomBrien** [comment]
Even if HA can sort the conversion, the app should (must) provide units otherwise there is an assumption and the whole thing will fall over in the morning. Personally I think the whole units could be looked at better. At the moment units are simply strings which is open to confusion. Personally I would favour implementing a simplified version of [astroPy](https://docs.astropy.org/stable/units/). That then could properly exploit unit preferences in HA

**Comment by ac0mputerguru** [comment]
I find this annoying, as well. It would be nice to have a configuration on the sensor in HA for m/ft.
