### ISSUE TITLE
Improve iOS location usage

### ISSUE THREAD

**Issue by olbjan** [home-assistant/iOS#520]
Feature request: improve location tracking on iOS, add options for more privacy

Based on user feedback and personal observation and testing, the current location tracking implementation while OK for most scenarios falls short with regards to the following limitations:
- No user configurable options
- Tracking is either all or nothing
- Location drift from significant location changes
- No use of standard location API
- Zone tracking close to useless if zones are close together

I would ask for a refactoring of the location code to facilitate the following goals:
- User configurable option to track and report only zones (basically uses only Visits Location Service), thus enabling automation without having a full trace of user movement. I think this would be a welcome privacy option for many.
- Change Location manager from one to two (maybe three?) subscriptions, moving the subscription to SignificantLocationChanges so a) SignificantLocationChanges can still be used to wake the app from suspend/terminated state and b) StandardLocation can be used with `pausesLocationUpdatesAutomatically = true`. The app should be able to re-start the StandardLocation tracking when woke via the SignificantLocationChange trigger.
- Drop the current location filter of accuracy >200m completely, instead use filtering based on comparing location distance to last known location, location accuracy and whether accuracy increased or decreased. Possibly activity as well. If say my phone is stationary at home and gets a SignificantLocationChange because of changes in the cell tower it's attached to, it should be possible to ignore this update as the new location circle will likely have increased in size more than the distance of the center of the circle has moved from the last known location. For more see the link below.
- Use StandardLocation smartly: Standard location should be used sparingly and not always on. It would be very useful to have it especially for commuting scenarios and areas with HA zones close together. I think something like the following would work:
1) Exit VisitLocation trigger or woke from Pause via SignificantLocationChange -> Start Standardlocation with something like kCLLocationAccuracyThreeKilometers. Always allow pause.
2) Based on activity or proximity to zones increase the accuracy required. We're not doing navigation so AccuracyThreeKilometers or AccuracyKilometer should be fine for driving. 
When the reported location reaches a defined distance to a zone (say distance = 2x AccuracyRequirement) then drop down to the next better AccuracyRequirement (maybe stop at NearestTenMeters). That way when approaching say Home, the app will report an increasingly correct position when it approaches zones and should work with zones in close proximity to each other. 
Anytime the app enters a visits zone, stop StandardLocation tracking.
The use of StandardLocation as opposed to just SignificantLocation and Visits could also be a user selectable checkbox, thus emporing users to choose whether they want improved tracking data for the cost of some battery or keep what is basically the current system or even drop to just geofencing.

This wish-list is inspired by an article that goes deeper into how this is coded here: https://badootech.badoo.com/ios-location-tracking-aac4e2323629

**Comment by monsieurlatte** [comment]
I would like to second this, I am so close to seeing if  Ican go back to the old app.  My automations are all sorts of broken with how the new app handles locations.  If I move my phone from my bedroom to my living room it will go from home to away and back, which triggers a bunch of things.

**Comment by TomBrien** [comment]
A new location service is bought in by #623 which will be in the next build. This is opt-in for now. Would be interested to know if that fixes this

**Comment by zacwest** [comment]
This is a helpful collection of thoughts about location, thank you. 

This is how I am thinking about locations right now:

- Visits is not super reliable, and it's only available after-the-fact for the most part. The system heuristics around it are fairly weak in my experience.

- We do use Standard Location API in the One Shot handling.

This is the part of the code that turns on location requests and gets better accuracy. This is done for background fetch, push notifications, manual updating, Shortcut requests, home screen actions and URL scheme requests.

- We should not rely on the location data generated from region events.  As of #697, we now poll for correct location data instead of using this.
- Pausing location services doesn't fit our use case. It only applies to actively pulling location data, which we do not do in the background - we already rely on significant location change to decide when to update.

---

One large potential improvement, sort of like you mentioned, is setting up regions around the user's current location, when not in an HA-defined zone, and using those to decide when to update location. This will largely affect the accuracy of the current location when reported outside of a zone, but won't improve anything like whether you are in a zone; for those fixes, the above is more relevant.

**Comment by zacwest** [comment]
I believe in the intervening time since I wrote the above, I've landed on being pretty satisfied with both the battery usage and overall test coverage and functionality of our location handling.
