### ISSUE TITLE
Graceful fallback for non SSL endpoint setup

### ISSUE THREAD

**Issue by ChrisWeiss** [home-assistant/iOS#575]
**Is your feature request related to a problem? Please describe.**
My Home Assistant does not have SSL. 
When going through the initial setup with the app, it finds my HA instance, but when trying to connect, it _requires_ an SSL connection and will fail. I'm forced to manually enter the URL.
This could well be a bug in that the auto-detect should not be returning a false-positive when detecting the HA endpoint (and not detecting the connection was actually non-SSL).

**Describe the solution you'd like**
Ideally, the app would notify the user that their connection is not secure and allow me to proceed setting the connection up as a standard HTTP connection.

**Describe alternatives you've considered**
I thought about detecting if the HA instance was on the same subnet or over wifi (indicating it was a local, internal connection), but there's probably some corner cases that wouldn't work there.

**Additional context**
Since I only access it within my internal network or via NabuCasa, I haven't bothered setting up SSL.

**Comment by dearthymcstain** [comment]
I am inclined to call this a bug rather than a feature request. Like ChrisWeiss, I only access my HA instance (which is running in a VM) using the internal network or Nabu Casa. Hence, I have never bothered to set up OpenSSL. I have been using the HA companion app for years with no issue, and as of yesterday, it's completely unusuable. I tried setting it up again from the beginning, and it chokes on the "Sensors Configured" portion of the setup with the message, "An SSL error has occurred and a secure connection to the server cannot be made." Why is this happening now?

**Comment by zacwest** [comment]
Sounds like you're using unnecessarily an https connection to your IP. Go to the app's settings, tap the server row at the top, and edit the internal URL to not include https.

There also is an occasional certificate expiration for your Nabu Casa URL which will require restarting your Home Assistant instance to pick up an unexpired one, which is an invalid certificate.

**Comment by dearthymcstain** [comment]
zacwest - thank you for your reply! It turns out all I needed to do was add the "internal URL" and it's working again. Thank you for your help!
