### ISSUE TITLE
"request_location_update" notifications on iOS return webhook error

### ISSUE THREAD

**Issue by jamieshaw** [home-assistant/iOS#576]
**iOS device model, version and app version**
Model Name: iPhone 11 Pro Max
Software Version: 13.4.1
App version: 2.0.0 (69)

**Home Assistant Core Version**
0.108.3

**Describe the bug**
Pushing a notification request to mobile devices with the special `request_location_update` returns an error in the Home Assistant log, as follows. The message is successfully parsed and returned by the iOS device as noted by the 'event log' within the app.
```
ERROR (MainThread) [homeassistant.components.mobile_app.webhook] Received invalid webhook payload: required key not provided @ data[11]['state']. Got None
```

**To Reproduce**
Send a notification to a iOS `mobile_app` entity with the following data:
```
service: notify.mobile_app_[user]
data:
    message: 'request_location_update'
```

**Expected behavior**
Successful update of the requested device's location with no warning message.

**Comment by SeanPM5** [comment]
Most of the iOS app sensors are not updating right now due to a bug that only occurs after updating to iOS 13.4. A fix has already been merged but Robbie needs to submit it to the App Store and go through app review. 

It's the same issue as https://github.com/home-assistant/iOS/issues/547  so closing this in favor of that one - you can follow the progress there.
