### ISSUE TITLE
Auto refresh

### ISSUE THREAD

**Issue by sandro-defender** [home-assistant/iOS#672]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sandro-defender** [comment]
Add option in app, to set page auto refresh time.
My lovelace ui always frees until i push any button..

**Comment by zacwest** [comment]
I don't think this is an option the app will adopt. You could add some JavaScript to the frontend which refreshes on an interval, but I'd prefer to think about solving the underlying problems rather than blowing them away with a refresh. Please open any issues related to the bugs you are experiencing.
