### ISSUE TITLE
Missing battery icons at 100% charge

### ISSUE THREAD

**Issue by bcmitri** [home-assistant/iOS#728]
**iOS device model, version and app version**
Model Name: iPhone XS
Software Version: iOS 13.5.1
App version: 2020.3 (5)

**Home Assistant Core Version**
0.111.4

**Describe the bug**
When the phone is at 100% charge, the icons are missing for the Battery Level and Battery State sensors 

**To Reproduce**
1) Allow the phone to charge to 100%. 
2) In any Lovelace view, observe the icons for the Battery Level and Battery State sensors. 

**Expected behavior**
Sensor icons are visible, as below:

![52073ED9-2F00-4156-A5AA-F750A7A34FF6](https://user-images.githubusercontent.com/53234043/86239398-9db9f900-bb75-11ea-8bbc-2881300b6cf1.jpeg)

**Actual behavior**
No icons are visible for either sensor, as below:

![369D180E-8369-4931-85FA-2698C385B5D7](https://user-images.githubusercontent.com/53234043/86239573-f12c4700-bb75-11ea-8346-7a0c18c69e22.jpeg)

**Comment by SeanPM5** [comment]
Just ran into this as well.

From Sensors section, it appears it's attempting to show `mdi:battery-100` for the icon, which does not exist in Material Design Icons. The 100% filled icon should just be `mdi:battery` instead. 

They do have an `mdi:battery-charging-100` ![charge100](https://i.imgur.com/PmEP4iv.png) icon however.

![image](https://i.imgur.com/aznERwH.png)
![image](https://i.imgur.com/KmAuEBR.png)
![image](https://i.imgur.com/amAOpTH.png)


Also I found another small quirk. Charged at 99%, yet the icon is showing `80` rather than `90` .

![image](https://i.imgur.com/YoFXI4Y.png)

My understanding is that having `device_class: battery` is supposed to handle all of this icon logic automatically. Perhaps there is some code in the app interfering with it.

**Comment by zacwest** [comment]
The math for battery icon when charging biases towards a smaller percent visible. I can't speak to the original intent, but I'm guessing it's trying to match a curve from somewhere else. 

https://github.com/home-assistant/iOS/blob/b648523799c065209d4b323baf3b2d22a0713e39/Shared/API/Webhook/Sensors/BatterySensor.swift#L26-L31

**Comment by mames13** [comment]
Hi was this problem ever solved for you? I'm having it now (in 2024). When the phone is charging, the  battery level sensor produces the prefix "battery" and not the suffix "-100". So my sensor does not produce "battery-100" to link to the proper icon. I'm pretty up to date on all of my Home Assistant and iOS software but can deep dive that further. Just curious if anyone else is having the same issue.
