### ISSUE TITLE
Set up with Nabu Casa account

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/iOS#771]
**Describe the solution you'd like**
It would be great if, when onbaording, we could enter a Nabu Casa username and password as an alternative to a URL for Nabu Cases Cloud-connected instances.

**Describe alternatives you've considered**

Currently we need to make a connection first or enter the long remote UI URL

**Comment by robbiet480** [comment]
@balloob or @pvizeli would need to weigh in on this.

**Comment by balloob** [comment]
Yes, this is possible. It would only help with **locating** the instance, it would not be able to help with accessing an instance.

This could be done by adding another webview to go through the Nabu Casa OAuth2 service and then hitting an endpoint to request the instance to open up the remote connection (in case it hasn't) and then fill in that url.

**Comment by robbiet480** [comment]
@balloob If you could provide some basic docs either here or to me/@zacwest we could take a look at getting it in soon.

**Comment by balloob** [comment]
I think that the use case would be relatively slim, because it means that people are setting up the app while not on the same network as Home Assistant but still have access to the Nabu Casa account.

Family members might not have access to the Nabu Casa account so this wouldn't help them. If we want to make it easier for them, we could maybe enable a new url scheme that Android/iOS can understand that automatically fills in the remotely accessible url. The user can then share this link with their family members.

**Comment by TomBrien** [comment]
Yep locating is what is needed I think. Onboarding with Nabu Casa instances is probably the most complicated and I feel it should be the smoothest.

**Comment by balloob** [comment]
But wouldn't it be easier if we could register our apps as a handler of a domain like https://mobile-setup.home-assistant.io and then allow users to share a link like https://mobile-setup.home-assistant.io/?instance%3Dhttps%3A%2F%2Fabcdefgh.ui.nabu.casa. It would be a website telling you to install the apps, and if the apps are installed it would actually trigger the app and it would parse out the url.

**Comment by balloob** [comment]
That way you can just text your family members: hey, to get access to our house, go to https://mobile-setup.home-assistant.io/?instance%3Dhttps%3A%2F%2Fabcdefgh.ui.nabu.casa to install the app and login with x/y.

Even better would be if we could include some one time authorization code in that url too. I am not sure if we can pass parameters to app store links ?

**Comment by TomBrien** [comment]
That'd be nice. Not sure about the one time auth although I suspect Zac or Robbie would have ideas there. What would be really nice, although I'm starting to spin this out too far, is if we could have a share button in app to allow sending the link through the normal iOS share system (I assume android has something similar)

**Comment by balloob** [comment]
Yeah, sharing would be nice. Once we have merged person/user creation, we could enable that. There is also a web API so we can just trigger it from the UI https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

**Comment by SeanPM5** [comment]
I think in the Home Assistant "Users" panel, we should have an "Email" field. 

When inviting a family member, you'd just go to the Users panel and type their first name and email to send them an invite by email. This would send them a nicely formatted welcome email with links to the mobile apps, a getting started tutorial, etc. They'd show up as a "Pending" user until accepting the invite. 

This makes it easier for both the user sending the invite (no need to explain any of this stuff), and for the person accepting the invite as they won't feel rushed and overwhelmed. 

Having an email address specified would come in handy for a bunch of other things too. For example if the user adds an integration that requires logging into a service, it could have their email pre-filled during the config flow. And maybe it could allow resetting a forgotten password by email rather than [these complicated steps](https://www.home-assistant.io/docs/locked_out/).

**Comment by balloob** [comment]
That is indeed a better approach.

Problem with email is that email needs to be sent via a paid service or else it will very likely end up in spam. With Home Assistant Cloud providing such a service means a) all links to get user accounts in local servers pass through unencrypted through our hands and b) we would allow anyone to be emailed unless we put it behind a HA Cloud login.
