### ISSUE TITLE
Zone Enter / Exit Firing with Inaccurate GPS Readings

### ISSUE THREAD

**Issue by ronaldheft** [home-assistant/iOS#810]
**iOS device model, version and app version**

Model Name: iPhone 11 Pro
Software Version: 13.6
App version: 2020.3.1

**Home Assistant Core Version**

0.112.4

**Describe the bug**

For the past week, I've been having an issues where nearby zones (several miles away) are occasionally firing enter / exit events. I've looked at my GPS accuracy as reported by the sensor, and I'm getting readings of 2500m, which would place me in the zones drawing a radius from my current location to 2500m away.

I see in the app logs there are messages that readings of >2500m are being ignored, but I don't think that's actually the case as I'm still getting these zone enter/exit readings.

I can resolve the issue by manually refreshing the app by pulling down to get a fresh location update, but shortly after the inaccurate GPS readings return.

I have tried with both "In-Development Updating" enabled and disabled.

**To Reproduce**

* Create a zone that is outside your current range, but less than 2500m away.
* Receive an inaccurate GPS reading.
* Notice zone enter/exit events are fired.

**Expected behavior**

* Zone enter/exit events should not be fired with inaccurate readings.
* GPS accuracy has gone down recently, and this was not an issue before. Is this related to new security enhancements in iOS 11.5?

**Screenshots**

**Additional context**
Happy to provide logs directly, just don't to upload here if it contains any sensitive information.

**Comment by zacwest** [comment]
2020.3.1 will log that it's ignoring inaccurate locations, but that's largely unrelated to what it sends - it's still going to send them up. The forthcoming 2020.4 version improves this (you can [sign up for the beta](https://community.home-assistant.io/t/public-beta-testing-is-now-open/70450) if you wish to test it -- just keep in mind, it is a beta) by rejecting anything whose accuracy exceeds 2km.

What you're running into is likely an iOS bug that can be resolved by restarting the device. For some reason beginning in iOS 13.5 or so and continuing in iOS 13.6 the system sometimes gets stuck in a mode where it will only give poor accuracy to applications in the background. We've been able to at least confirm it isn't just HA that gets stuck in this poor accuracy. Eventually the app will alert when it detects this, but right now it does not.

If a restart of your device does not solve this, it would be helpful for you to share some of the logs from the device. You can do this in the App Configuration screen and exporting them. Feel free to hop [into Discord](https://www.home-assistant.io/help/) in the #ios channel if you want to share them privately, since they will contain information like your historical locations.

**Comment by ronaldheft** [comment]
Thanks. I restarted and for now my accuracy appears normal. I'll keep that in mind and look for the fix in the next version.

**Comment by TomBrien** [comment]
@zacwest did you and Robbie ever decide to have a call with Apple on CL stuff? This seems to be a problem on their side

**Comment by zacwest** [comment]
Unless it's a "I am holding it wrong" kind of thing (and that we've noticed it in other apps, and restarting fixes it, makes me think it is not) Apple's Developer Technical Support isn't very helpful. You file a bug and pray someone eventually solves it one day, or not.
