### ISSUE TITLE
Unable to copy/paste on IOS mobile app

### ISSUE THREAD

**Issue by duceduc** [home-assistant/iOS#823]
**iOS device model, version and app version**
Model Name: iPhone X
Software Version: 13.5.1
App version: 2020.4 [0.1130]

**Home Assistant Core Version**
0.113.0

**Describe the bug**
Unable to copy or paste in mobile app

**To Reproduce**
Navigate to developer tool and paste something in any field.

**Expected behavior**
Long press on screen should provide several options.

**Comment by TomBrien** [comment]
Cheers. Just to confirm pasting works in Safari.

**Comment by zacwest** [comment]
Pasting in the regular fields works, it appears that his exclusively happens in the code editor. I also see some visual differences versus Safari: the cursor in Safari is shorter, wider and blue and in the app it's taller, thinner and black.

**Comment by RyanMorash** [comment]
The way I end up pasting in the code editor is by using the three-finger spread gesture.

**Comment by bluehz** [comment]
> The way I end up pasting in the code editor is by using the three-finger spread gesture.

iOS 14.0 (18A5332f)
Confirming the three finger method works as workaround.

**Comment by IIAIronWolf** [comment]
I also had this issue. With the iOS team change, I had to log back in to the HA iOS App and could not paste my password. Likewise, could not retrieve my 2FA code, because when you leave the iOS app, HA reloads when you come back, causing you to have to start the login from the beginning again.

**Comment by artkrz** [comment]
Not being able to paste password as well. The app should support autofill. Not being able to switch to other app and come back is even worse as it makes impossible to log in with 2fa.

**Comment by zacwest** [comment]
There are a few issues at play here.

- This ticket is referring specifically to the code editor not supporting paste in the latest iOS 13 and such. This is a separate issue, I believe, from iOS 14 issues.
- Paste not working on iOS 14 is a recent iOS 14 beta occurrence, but we do not have an individual issue tracking it yet.
- The app restarting onboarding when changing apps is the iOS 14 crash being tracked in #822.
- Password managers and other autofill not working in the app is best tracked in https://github.com/home-assistant/frontend/issues/1622 -- unfortunately this is entirely beyond the app's control because the login forms are all webviews from the frontend.

Unfortunately part of running iOS betas is random things like this. For example, the crash only started in beta 3 and it really does seem like an Apple bug. There's a partial workaround available [in TestFlight builds](https://www.home-assistant.io/ios/beta) if you're willing to grab the beta app.
