### ISSUE TITLE
Location update not always working, getting error "Didn't update: location update from the past"

### ISSUE THREAD

**Issue by jeroenjacobs79** [home-assistant/iOS#833]
**iOS device model, version and app version**
iPhone 7
13.5.1

Model Name:
Software Version: 
App version: 

**Home Assistant Core Version**
Home Assistant 0.111.4

**Describe the bug**

App is not always updating my location. Sometimes it works, but sometimes I get the following error in the event log:

`Didn't update: location update from the past`

I verified the time and date settings on both my mobile and HA server. They are correct.

**To Reproduce**

Not sure. It seems to happen at random.

**Expected behavior**

Correct location update.

**Screenshots**

**Additional context**

**Comment by zacwest** [comment]
The log is benign (it'll be silenced by fixing #816) -- chances are you are experiencing an iOS bug which causes significantly inaccurate locations. Do you have any logs indicating this as a reason? Restarting your phone should help.

If you don't see any for that, can you share what other reasons for failure you're seeing?

**Comment by jeroenjacobs79** [comment]
No, nothing indicates that. Both me and my girlfriend are using HA app, and none of our devices are listed at "home" when we arrived home at the same time. Seems weird that both our phones are triggering the same IOS bug at the same time.

**Comment by zacwest** [comment]
I would expect an entry about old locations in the logs right now every time the app launches freshly, because the system sends an old one at that point (which is why the log isn't likely the cause).

Do you have any events that look like "zone.x entered" or exited? Other didn't updates? Anything tagged "location update" really.

If not, it might be useful to take a look at your raw logs ("export log files"). It is worth noting this will contain personal data like raw locations. You can upload it here or if you'd like it kept private you can hop on [Discord](https://www.home-assistant.io/help/) and join #ios to discuss the issue.

**Comment by zacwest** [comment]
I believe since this issue was opened, #841 came to light which may explain some issues entering and exiting zones. I believe this was the last known location issue, so if you're still experiencing a problem, the above steps will be useful to debug. You can give the fixes a try in 2020.6. At the time of writing this, it is not yet in the App Store, but you can try the [TestFlight](https://www.home-assistant.io/ios/beta).
